### ISSUE TITLE
Config should be stored in Secret instead of ConfigMap

### ISSUE THREAD

**Issue by theduke** [grafana/helm-charts#101]
The main config or especially provisioners often contain secrets.

Currently this is stored in a `ConfigMap`, which is suboptimal.

**Comment by AllexVeldman** [comment]
Datasources and Notifiers sidecar support loading the configs from Secrets, and the docs mention that the dashboards can also be provided as Secrets
https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-datasources

The Admin user and password can also be provided in a Secret using `admin.existingSecret`.

Any other Secret value in the grafana.ini seems to also be supported as a generic setup:
https://github.com/grafana/helm-charts/tree/main/charts/grafana#how-to-securely-reference-secrets-in-grafanaini
Although I haven't used that one yet.

**Comment by theduke** [comment]
I missed that
