### ISSUE TITLE
[agent-operator]: Helm release upgrades fail, immutable Deployment selector labels use mutable chart and app version info

### ISSUE THREAD

**Issue by stevo-f3** [grafana/helm-charts#1010]
Affected: agent-operator chart version 0.1.5

Deployment selector is referencing `ga-operator.labels` template: https://github.com/grafana/helm-charts/blob/main/charts/agent-operator/templates/operator-deployment.yaml#L16

`ga-operator.labels` template is referencing, mutable across helm release upgrade, chart and app (operator) versions
https://github.com/grafana/helm-charts/blob/main/charts/agent-operator/templates/_helpers.tpl#L40-L43

The selector in Deployment, ReplicaSet, and DaemonSet objects is immutable as of the apps/v1beta2 API. See kubernetes/kubernetes#50808

Current workaround: delete and have recreated grafana-agent-operator helm release and grafana-agent-operator Deployment with it.

**Comment by hjet** [comment]
Closed by https://github.com/grafana/helm-charts/pull/1097
