### ISSUE TITLE
loki-distributed: ruler s3 storage not picking up rules files.

### ISSUE THREAD

**Issue by uberbrodt** [grafana/helm-charts#1020]
I'm running chart version 0.38.1 and I'm unable to use the s3 storage backend for the ruler. I've updated the gateway to correctly proxy requests to the ruler API as I describe in #964 and was successful with local storage picking up my rules. However, when I swapped out ruler storage with S3, it is unable to find my rules.

Uploaded rules files in bucket under 'fake' path in s3:

```
$  aws s3 ls --recursive s3://sy-ops0-loki-rules/
2022-02-08 10:25:31        406 fake/rules.yaml
```
Added following section to loki config:
```
        ruler:
          enable_api: true
          storage:
            type: s3
            s3:
              s3: s3://us-west-2
              bucketnames: sy-ops0-loki-rules
```

Ruler logs:

```
level=info ts=2022-02-08T16:24:00.023685667Z caller=main.go:129 msg="Starting Loki" version="(version=, branch=, revision=)"
level=info ts=2022-02-08T16:24:00.024480349Z caller=server.go:239 http=:3100 grpc=:9095 msg="server listening on addresses"
level=info ts=2022-02-08T16:24:00.025193071Z caller=memberlist_client.go:392 msg="Using memberlist cluster node name" name=loki-ruler-8d5ddd77f-qqg5m-a23d72db
level=info ts=2022-02-08T16:24:00.025599457Z caller=mapper.go:46 msg="cleaning up mapped rules directory" path=/rules
level=info ts=2022-02-08T16:24:00.030324193Z caller=module_service.go:59 msg=initialising module=memberlist-kv
level=info ts=2022-02-08T16:24:00.030676989Z caller=module_service.go:59 msg=initialising module=server
level=info ts=2022-02-08T16:24:00.032766392Z caller=module_service.go:59 msg=initialising module=ring
level=info ts=2022-02-08T16:24:00.035267662Z caller=ring.go:275 msg="ring doesn't exist in KV store yet"
level=info ts=2022-02-08T16:24:00.035498916Z caller=module_service.go:59 msg=initialising module=ingester-querier
level=info ts=2022-02-08T16:24:00.035557567Z caller=module_service.go:59 msg=initialising module=store
level=info ts=2022-02-08T16:24:00.035885652Z caller=module_service.go:59 msg=initialising module=ruler
level=info ts=2022-02-08T16:24:00.036043105Z caller=ruler.go:438 msg="ruler up and running"
level=info ts=2022-02-08T16:24:00.036687555Z caller=loki.go:272 msg="Loki started"
level=info ts=2022-02-08T16:24:00.054778905Z caller=memberlist_client.go:504 msg="joined memberlist cluster" reached_nodes=5
level=info ts=2022-02-08T16:24:17.530523118Z caller=api.go:403 org_id=fake traceID=3bed545687849b99 msg="no rule groups found" userID=fake
level=info ts=2022-02-08T16:24:37.621129795Z caller=api.go:403 org_id=fake traceID=07f4296b12d26169 msg="no rule groups found" userID=fake
level=info ts=2022-02-08T16:24:57.718772556Z caller=api.go:403 org_id=fake traceID=0cdaebf3ed4b4e24 msg="no rule groups found" userID=fake
level=info ts=2022-02-08T16:25:17.810531527Z caller=api.go:403 org_id=fake traceID=7d1586ae7cd85929 msg="no rule groups found" userID=fake
level=info ts=2022-02-08T16:25:37.961388733Z caller=api.go:403 org_id=fake traceID=4de0103423029a4b msg="no rule groups found" userID=fake
level=info ts=2022-02-08T16:25:58.085773847Z caller=api.go:403 org_id=fake traceID=08165f3c34eca26e msg="no rule groups found" userID=fake
level=info ts=2022-02-08T16:26:18.166702389Z caller=api.go:403 org_id=fake traceID=7ff7a534d03aed04 msg="no rule groups found" userID=fake
level=info ts=2022-02-08T16:26:38.312595206Z caller=api.go:403 org_id=fake traceID=4da88113ac56c60d msg="no rule groups found" userID=fake
level=info ts=2022-02-08T16:26:58.442064282Z caller=api.go:403 org_id=fake traceID=2a16b0d82fbd704f msg="no rule groups found" userID=fake
level=info ts=2022-02-08T16:27:18.578582309Z caller=api.go:403 org_id=fake traceID=5692eb73dca7d187 msg="no rule groups found" userID=fake
...
```

**Comment by LinTechSo** [comment]
Hi, any updates ?

**Comment by fr-chengxuanli** [comment]
expect some documentation for best practices for configuration as code for both grafana and loki

**Comment by pof-arvindkonar** [comment]
Just fyi. You have to use cortextool to upload the rule files. You can't manually create fake and upload it there. It is better to actually use configmap instead

**Comment by dragoangel** [comment]
@dannykopping I think there would be much fewer questions if https://grafana.com/docs/loki/latest/configuration/#ruler at section storage would mention [link you posted](https://grafana.com/docs/loki/latest/rules/#interacting-with-the-ruler) 😊.

**Comment by dragoangel** [comment]
@dannykopping actually cortextool not working :(, it throws 404, do you have working setup with s3 and new loki helm (v5.8.0) chart with Loki gateway?

**Comment by phantomedc** [comment]
Loki's documentation is really confusing

**Comment by mwtzzz** [comment]
There's two ways to load and store rules files in SimpleScaleable mode:
a) in S3 bucket via API call
b) in local pod storage via yaml files

## S3: ##
Loki ruler with s3 storage works like this:

1. loki-backend pods periodically scan the S3 bucket. It is looking for binary files that contain the rules data. The names of the files are based on a hash of Loki namespace and other things.
2. The only way to add rules files to S3 is to use the Loki API. A rule created by an API POST call is added to the bucket under `/rules/{tenant_id}/{hash part2}/{hash part 2}`.
3. Rules files (yaml, text files, etc) *manually* added to the bucket are *ignored*
4. The loki-backend pods periodically scan the S3 bucket, find the rules and create a yaml copy of it in in each pod `/var/loki/rules-temp/<org_id>/<namespace>`. This temp folder is the "working area" where the ruler reads the rules.
5. Any files *manually* added to `/var/loki/rules-temp` are ignored and deleted
6. Any files manually added to the `/rules/`, `/var/loki/rules` are ignored.
7. `/loki/rules` is read-only and does not appear to be used.

## Local pod filesystem ##

1. loki-backend pods mount an `emptyDir` at `/rules`. At first there are no files in it. But, the backend statefulset also has a k8s-sidecar whose job is to search configMaps and secrets for a label (of your choosing). These configMaps and secrets contain the rules. The sidecar will copy these rules to files in the `/rules/{tenant_id}` folder, thus making them available to the ruler. 
2. the backend ruler periodically scans `/rules/{tenant_id}` and loads any rules it finds.

The `sidecar:` helm values get applied to the init container in the loki-backend stateful set.

There is no need to configure `extraVolume` or `extraVolumeMounts`. These get ignored anyway when the helm chart creates the sidecar, so it would be pointless to use them. There is no way to tell the helm chart to replace or rename the default volumeMount `sc-rules-volume`, so it's best to use the default.

All you have to do is create a configMap with contents this like:

    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: loki-rules
      namespace: your k8s namespace
      labels:
        loki_rule: "DevTeam"
    data:
      dev-team-rules.yaml: |
        groups:
        - name: linuxrulegroup
          rules:
            - alert: rc-local-errors
              expr: |
                <logql expression>
    ...

The metadata label from the ConfigMap must match the label you pass to the sidecar in helm.
