### ISSUE TITLE
[loki-simple-scalable] Gateway nginx config does not include all Ruler api endpoints 

### ISSUE THREAD

**Issue by ledouxpl** [grafana/helm-charts#1041]
According to the latest [Loki api](https://grafana.com/docs/loki/latest/api/), the nginx configuration created from the `loki-simple-scalable` helm chart is missing the `/prometheus` endpoints:

- GET /prometheus/api/v1/rules
- GET /prometheus/api/v1/alerts

This leads to Grafana having issues reaching the ruler API when Loki's datasource is pointing to the loki-gateway's endpoint.

I was able to patch the issue by adding the following to my `nginx.conf`:

```
location ~ /prometheus/api/.* {
   proxy_pass       http://loki-read.logging.svc.cluster.local:3100$request_uri;
}
```

**Comment by selfsk** [comment]
With latest chart release (1.0.0), here is a small snippet for your `values.yaml` file to implement this workaround.

```
# a hack to enable Loki ruler api via gateway
# proxy_pass URL is copied from existing config map, depending on how you name your installation- name could/will change
gateway:
  nginxConfig:
    serverSnippet: |
      location ~ /prometheus/api/.* {
        proxy_pass       http://loki-read.loki.svc.cluster.local:3100$request_uri;
      }
```
