### ISSUE TITLE
grafana.smtp.existingSecret not overwriting grafana.ini in 2.6.1 in loki-stack chart

### ISSUE THREAD

**Issue by griftir** [grafana/helm-charts#1044]
After upgrading loki-stack chart from 2.1.0 to 2.6.1, the grafana.smtp.existingSecret in values.yaml is not overwriting the user and password sections of grafana.ini. 

Logs no longer show config being overridden for smtp user and password, inspecting the grafana.ini on the running grafana container shows no values for user/password.

Workaround is to hardcode user/password in grafana.ini.smtp.user and grafana.ini.smtp.password of the values file.

**Comment by XDavidT** [comment]
duplicate: https://github.com/grafana/helm-charts/issues/72
