### ISSUE TITLE
add config option for injecting sidecar into gateway (nginx) deployment to work around UDP issues

### ISSUE THREAD

**Issue by joemiller** [grafana/helm-charts#1058]
We've run into an issue with the gateway (nginx) component in the loki-distributed chart that causes Loki to stop ingesting new logs. It appears this can happen when the kube-dns (coredns in most modern clusters) pods are restarted for example during nodepool upgrades/drains/etc. The observed error message is a stream of 499's in the gateway log:

```
10.194.148.169 - - [17/Feb/2022:21:08:28 +0000]  499 "POST /loki/api/v1/push HTTP/1.1" 0 "-" "promtail/" "-"
10.194.90.195 - - [17/Feb/2022:21:08:28 +0000]  499 "POST /loki/api/v1/push HTTP/1.1" 0 "-" "promtail/" "-"
```

Things generally stay in this broken state until gateway pods are deleted/restarted or a SIGHUP is sent to the nginx proc.

We can recreate the issue by killing/restarting the coredns (`kube-dns.kube-system`) pods in a cluster. The issue occurs because of how nginx maintains the same udp source port on all DNS queries. It's actually an issue with Kubernetes and UDP services and a specific behavior of nginx's resolver. A deeper technical explanation is available here: https://github.com/kubernetes/kubernetes/issues/26309

The best fix so far seems to be injecting a dnsmasq sidecar into the nginx deployment which has different behavior when performing DNS queries. An example of such a sidecar is in the same issue in this comment: https://github.com/kubernetes/kubernetes/issues/26309#issuecomment-372999912

It would be great if the helm chart made it possible to optionally add a sidecar to the gateway deployment template so that we can workaround the nginx/k8s udp issue.

Would this project consider accepting an option to add a sidecar to the gateway deployment template in the loki-distributed chart?

**Comment by joemiller** [comment]
proposed implementation in https://github.com/grafana/helm-charts/pull/1067

**Comment by joemiller** [comment]
Closing this because it can be worked around using a sidecar like go-dnsmasq as described in #1067 via the extra sidecar injector config in: https://github.com/grafana/helm-charts/pull/1133 makes

**Comment by arnaudclerc** [comment]
this is not yet available in regular loki helm ([artifactHub](https://artifacthub.io/packages/helm/grafana/loki) 5.15.0)
the changes applied to loki-distributed should be applied to the main helm chart to avoid ugly workarounds.

Thank you
