### ISSUE TITLE
critical expat vuln in k8s-sidecar:1.15.1

### ISSUE THREAD

**Issue by wkaczynski** [grafana/helm-charts#1063]
k8s-sidecar images up to 1.15.5 expose 2 critical expat security vulnerabilities
already addressed in k8s-sidecar 1.15.6
see: https://github.com/kiwigrid/k8s-sidecar/issues/164

**Comment by wkaczynski** [comment]
Here you go: https://github.com/grafana/helm-charts/pull/1064

**Comment by zanhsieh** [comment]
Merged.
