### ISSUE TITLE
[mimir-distributed] helm install failing

### ISSUE THREAD

**Issue by saiyam1814** [grafana/helm-charts#1145]
`
helm install demo grafana/mimir-distributed -f small.yaml 

Error: INSTALLATION FAILED: failed to download "grafana/mimir-distributed"`

**Comment by TaylorMutch** [comment]
Workaround I have for this is to just clone this repo and reference it locally for now.

**Comment by krajorama** [comment]
Thank you for the feedback!

We tested this after publishing and I double checked now. Is it still failing in your case, what does `helm search repo` tell you?
Mine includes currently:
```
grafana/mimir-distributed     	0.1.2        	2.0.0      	Grafana Mimir
```

**Comment by krajorama** [comment]
closing stale issue
