### ISSUE TITLE
[mimir-distributed] Missing service monitors for all components

### ISSUE THREAD

**Issue by TaylorMutch** [grafana/helm-charts#1147]
When attempting to upgrade to mimir-distributed from https://github.com/cortexproject/cortex-helm-chart, all the service monitors are removed. Can we add these?

**Comment by TaylorMutch** [comment]
Cheers I will try this out today!

**Comment by krajorama** [comment]
Thank you in advance @TaylorMutch , let me know how it went, we can reopen the issue any time.

@zanhsieh Thank you for the review on the PR, I was waiting for feedback on it before merging though. Should have made it Draft probably.

**Comment by ryan-dyer-sp** [comment]
@krajorama I see 0.1.3 of the chart was "released" but it doesnt seem to be available on the helm repo.
```
> helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "grafana" chart repository
> helm repo list
grafana                         https://grafana.github.io/helm-charts
> helm search repo mimir
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
grafana/mimir-distributed       0.1.2           2.0.0           Grafana Mimir
```

**Comment by ryan-dyer-sp** [comment]
0.1.4 is now available in the repo.
