### ISSUE TITLE
[mimir-distributed] Missing option to use configmap instead of secret for mimir config

### ISSUE THREAD

**Issue by TaylorMutch** [grafana/helm-charts#1150]
In cortex-helm-chart we have the option to use a [configmap](https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L37) for specifying the configuration instead of a secret.

This is useful when there are no secret values stored as part of the configuration, and using `helm diff` to review proposed configuration changes is part of the upgrade flow.

@krajorama : make this the default in the upcoming chart.

**Comment by krajorama** [comment]
Hi. That seems fair. It's a bit more involved than it seems as we'd like to reuse this chart in the next version of [enterprise-metrics], which is under development right now. Going to incorporate this request.
