### ISSUE TITLE
[mimir-distributed] Link in documentation broken

### ISSUE THREAD

**Issue by muffl0n** [grafana/helm-charts#1176]
> See [Grafana Mimir documentation](https://grafana.com/docs/mimir/v2.0.x) for details on storage types and documentation.

The above link on page https://github.com/grafana/helm-charts/tree/main/charts/mimir-distributed is broken.

**Comment by krajorama** [comment]
woops seems like missing `/` at the end, fixing

**Comment by muffl0n** [comment]
Thank you!
