### ISSUE TITLE
[mimir-distributed] Option to disable AlertManager

### ISSUE THREAD

**Issue by paalkr** [grafana/helm-charts#1178]
The Cortex helm chart has the ability to disable AlertManager.
https://github.com/cortexproject/cortex-helm-chart/blob/b69318fb683d4c56ca3e1658b87024596928c221/values.yaml#L161-L162

I think Mimir should have this capability as well. We do run an external highly available AlertManager, so the AlertManager that ships with Mimir isn't needed.

**Comment by krajorama** [comment]
please reopen if it is still an issue, thank you
