### ISSUE TITLE
[mimir-distributed] Make it possible to run mimir-distributed on OpenShift 

### ISSUE THREAD

**Issue by patrickabrennan** [grafana/helm-charts#1217]
Memcache needs a service account so that the mimir-distributed helm chart can be installed on non-vanilla k8s distributions like OpenShift. Without this service account, the memcached deployment used in the Helm chart doesn't conform to the security requirements of OpenShift. 

Blocked on https://github.com/grafana/helm-charts/issues/1315. 

------- more detail --------

The Bitnami 5.5.2 memcache chart does not provide for a service account name. This means that it will use the "default" service account in the namespace it is deployed. This creates two problems. 1) It is not a K8s best practice - all applications should have its own service account and 2) The memcache chart from Bitnami has a `runAsUser: 1001` setting. While this is normally ok for some k8s distributions like GKE which uses Pod Security Policy (PSP), this does not work for OpenShift which uses Security Context Constraints (SCC).  In OpenShift the default SCC is `restricted` and it does not allow the use of a `runAsUser: 1001`, it uses a range which is randomly generated when a namespace (what OpenShift calls a project) is created. To use `runAsUser: 1001` one has to either use an SCC such as `anyuid` which is one of the 8 built in SCC's or create ones own SCC. In order to use an SCC other than the default of `restricted` one needs a service account for the application. I would also note that the newer versions of the Bitmani memcache chart has a setting for a service account. While using the default service account is possible (connect the RBAC permission with the proper SCC) it is generally not recommended.

**Comment by 09jvilla** [comment]
Draft PR:
https://github.com/grafana/helm-charts/pull/1329
