### ISSUE TITLE
[mimir-distributed] Was v2.0.0 release intentional?

### ISSUE THREAD

**Issue by stevehipwell** [grafana/helm-charts#1236]
I was wondering if this release was intentional or a typo?

**Comment by 09jvilla** [comment]
@stevehipwell can you say more?

**Comment by stevehipwell** [comment]
@09jvilla the mimir-distributed chart version jumped from v0.1.8 to v2.0.0 which seemed like a potential typo so I opened this issue.

**Comment by krajorama** [comment]
Hi, it was intentional yes,  please see the CHANGELOG for the reasoning. In short: the chart was derived from enterprise-metrics with the intention of reusing it as a subchart, however that lead to too many complications from user and developer point of view (see #1203).
