### ISSUE TITLE
[loki-simple-scalable] ServiceMonitor causes metric duplication

### ISSUE THREAD

**Issue by wappam** [grafana/helm-charts#1237]
There is metric duplication by the servicemonitor picking the additional headless service for the write and read components.

The same issue have been fixed on the loki-distributed helm chart; https://github.com/grafana/helm-charts/issues/597

**Comment by LinTechSo** [comment]
Hi, any updates ?

**Comment by zanhsieh** [comment]
@LinTechSo 
If you have idea how to fix, would you mind to PR it please?

**Comment by wappam** [comment]
I am working on a fixed, [here](https://github.com/wappam/helm-charts/commit/333bb97f6fa2905989537a13c1fd95e424583ca1)

Just bare with me, its my first PR ever and I am not sure how.

**Comment by zanhsieh** [comment]
@wappam 
I could approve that later, but bear in mind @trevorwhitney seems not really care loki-simple-scalable any more. In other words, if you'd like to get the original maintainer approval then it will be a long long time.

My own previous PR below, which is just adapting some previous PR that I can't get DCO signoff from that original author.
https://github.com/grafana/helm-charts/pull/1188
