### ISSUE TITLE
[mimir-distributed] Getting an error when setting Ingress enable to True in Helm chart values file. 

### ISSUE THREAD

**Issue by BitKickerBHS** [grafana/helm-charts#1244]
When deploying the mimir-distributed using helm chart values.yaml file if the Ingress is enabled: true I get the following error during deployment. 

Error: template: mimir-distributed/templates/nginx/ingress.yaml:46:25: executing "mimir-distributed/templates/nginx/ingress.yaml" at <include "mimir.nginxFullname" $>: error calling include: template: no template "mimir.nginxFullname" associated with template "gotpl".

Could this be caused by the _helpers.tpl not being updated in the helm chart? If this is just an issue with my config I apologize for the disruption.

**Comment by agrahamlincoln** [comment]
I hit this too, I looked around and couldn't find `mimir.nginxFullname` template defined anywhere in the helm chart

**Comment by BitKickerBHS** [comment]
The following needs to added to the top of charts/mimir-distributed/templates/nginx/_helpers.tpl

{{/*
nginx fullname
*/}}
{{- define "mimir.nginxFullname" -}}
{{ include "mimir.fullname" . }}-nginx
{{- end }}

Correct nginx _helpers.tpl to define  mimir.nginxFullname based off mimir.fullname .

**Comment by krajorama** [comment]
fix in the works in #1260

**Comment by krajorama** [comment]
please test with 2.0.5, #1260 is merged

**Comment by krajorama** [comment]
should be fixed , please reopen issue if not
