### ISSUE TITLE
[mimir-distributed] extraContainers support

### ISSUE THREAD

**Issue by samcday** [grafana/helm-charts#1264]
We've encountered issue #1058 in both our loki-distributed and mimir-distributed deployments. We worked around it in Loki using the dnsmasq sidecar approach, which was easy thanks to `.gateway.extraContainers`. Unfortunately the Mimir Helm chart does not offer the same support.

We're working around this with a Helm post renderer to smoosh the necessary bits in place. Would be nice if supplying extra containers to the Mimir nginx was properly supported though.

**Comment by krajorama** [comment]
I think https://github.com/grafana/mimir/pull/2394 solves this for nginx and it was there for the enterprise gateway. Please reopen if you do not agree
