### ISSUE TITLE
[grafana] helm chart to support volumes and volumeMounts for imageRenderer

### ISSUE THREAD

**Issue by yzargari** [grafana/helm-charts#1267]
Hello,

I'm working on launching Grafana in my Kubernetes cluster using your helm chart. I configured Grafana to listen on HTTPS instead for HTTP with a certificate signed by my internal CA.
When I'm setting up the image renderer to connect to Grafana over HTTPS, it fails because `Error: net::ERR_CERT_AUTHORITY_INVALID` - which makes sense. I want to be able to mount the certificate authority pem file and make the renderer trust it - but the helm chart won't let me define any volumes and volumeMounts.

Can someone look into that?
Would you be willing to consider a PR with this fix if I submit one?

Thanks,
Yosi

**Comment by bradleypettit** [comment]
Image renderer pods now support extraConfigmapMounts, extraSecretMounts, extraVolumeMounts, extraVolumes with https://github.com/grafana/helm-charts/pull/3178.
