### ISSUE TITLE
Installation problem, Mimir pods do not come up

### ISSUE THREAD

**Issue by nasirudheen** [grafana/helm-charts#1277]
Hi,
I am trying to deploy mimir-distributed on 6 node Kubernetes cluster with `rook` based `ceph` cluster as S3 storage backend. The helm package is completed with status as `deployed`. But all the pods except `memcached-*` are perpetually staying in `CrashLoopBackOff`. The logs of  these crashing pods are giving the following error,

`level=info ts=2022-04-22T17:55:59.021628128Z caller=main.go:193 msg="Starting application" version="(version=2.0.0, branch=HEAD, revision=9fd2da5)"
level=error ts=2022-04-22T17:55:59.021808927Z caller=log.go:60 msg="error running application" err="open ./metrics-activity.log: read-only file system\nfailed to create activity file\ngithub.com/grafana/mimir/pkg/util/activitytracker.getMappedFile\n\t/__w/mimir/mimir/pkg/util/activitytracker/activity_tracker.go:177\ngithub.com/grafana/mimir/pkg/util/activitytracker.NewActivityTracker\n\t/__w/mimir/mimir/pkg/util/activitytracker/activity_tracker.go:60\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).initActivityTracker\n\t/__w/mimir/mimir/pkg/mimir/modules.go:139\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:120\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:426\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:195\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror initialising module: activity-tracker\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:122\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:426\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:195\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"`

Other relevant info,

OS on all nodes : Rocky Linux 8
Kubernetes; 1.23.5
Helm output:

`[root@mimir1 mimir]# helm install grafana-mimir grafana/mimir-distributed -f mimir-distribute-values.yaml --create-namespace -n grafana-mimir

W0422 17:54:14.830674  154605 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0422 17:54:14.951148  154605 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME: grafana-mimir
LAST DEPLOYED: Fri Apr 22 17:54:12 2022
NAMESPACE: grafana-mimir
STATUS: deployed
REVISION: 1
TEST SUITE: None
`

The values file passed is attached along with this.
[mimir_values.txt](https://github.com/grafana/helm-charts/files/8543136/mimir_values.txt)

Please let me know if there is anything else required from my side to help me.
Thanks,
Nasir

**Comment by krajorama** [comment]
Hi,  we've moved the activity tracker setting to the configuration for consistency (from version 0.1.7->2.0.0 of the chart). Please add 
```yaml
activity_tracker:
      filepath: /data/metrics-activity.log
```
to mimir.config somewhere, see https://github.com/grafana/helm-charts/blob/4f375f541493e3f3d93f4cc423684548644ce332/charts/mimir-distributed/values.yaml#L56

My apologies for the inconvenience, adding the enterprise metrics as an option was a big change.

**Comment by krajorama** [comment]
I'm adding validation for this :  #1290

**Comment by 09jvilla** [comment]
Moving this issue to closed since @krajorama has added a check for this and the original problem was resolved.
