### ISSUE TITLE
[mimir-distributed] PodSecurityPolicy deprecated

### ISSUE THREAD

**Issue by krajorama** [grafana/helm-charts#1288]
https://kubernetes.io/docs/concepts/security/pod-security-policy/
is being deprecated. Prepare for switching over to https://kubernetes.io/docs/concepts/security/pod-security-admission/ .

~~Should this be done in a major upgrade where we bump the required Kubernetes version as well? We require 1.10 kubernetes, but that from March 2018.~~

We've bumped the required Kubernetes version to 1.20 (https://github.com/grafana/mimir/pull/2297)

**Comment by dimitarvdimitrov** [comment]
PSP is covered by this PR https://github.com/grafana/mimir/pull/2870

working for >=1.25 will be covered by https://github.com/grafana/mimir/issues/2595

**Comment by dimitarvdimitrov** [comment]
cc @mattmendick - I found the PR we talked about in the meeting

**Comment by rubenvw-ngdata** [comment]
I think this is still being used in the latest released version of the helm chart, and still present in the current helm chart
See https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/podsecuritypolicy.yaml

**Comment by MaxDiOrio** [comment]
This is not fixed in 4.4.1 of the chart.  Still getting the error when upgrading:
W0608 11:37:05.530688   86987 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

**Comment by dimitarvdimitrov** [comment]
this seems like a warning, not an error. Does it also prevent from installing the chart?

Also see https://github.com/grafana/mimir/issues/5238 about upgrading to 1.25 with the chart. Apparently helm doesn't handle this very well.

**Comment by MaxDiOrio** [comment]
Not a prevent install or upgrading the chart, but it will if it's not resolved before they remove PodSecurityPolicy before v1.25

**Comment by diptripa** [comment]
We are not able to install the helm chart because of the podsecuritypolicy not disabled.. Even if I set mimir.rbac.usePodSecurityPolicy to false, it somehow creates the psp.

**Comment by dimitarvdimitrov** [comment]
@diptripa please open a new issue in grafana/mimir since this has been closed for 11 months now (and maybe have a look at [Migrate the Helm chart from version 4.x to 5.0](https://grafana.com/docs/helm-charts/mimir-distributed/latest/migration-guides/migrate-helm-chart-4.x-to-5.0/) if you haven't already)

**Comment by ramfjord** [comment]
@diptripa check out the _helpers file or grep for that and you'll see that it's not a particular value but a function, hence `include` is used.  But in reality just listen to the other dude who replied
