### ISSUE TITLE
[mimir-distributed] Add structuredConfig similar to loki-distributed

### ISSUE THREAD

**Issue by Skaronator** [grafana/helm-charts#1292]
The loki-distributed helm chart provides a `structuredConfig` option which allows overwriting specific key/values in the huge `loki.config` template without maintaining/copy-pasting the whole config in your own values.

https://github.com/grafana/helm-charts/blob/8c8bcc17f19185f968c31d1f4f66366ce7b589d9/charts/loki-distributed/values.yaml#L185

https://github.com/grafana/helm-charts/blob/8c8bcc17f19185f968c31d1f4f66366ce7b589d9/charts/loki-distributed/templates/configmap.yaml#L8-L10

I would like to see a similar feature in the mimir-distributed helm chart.

My usecase would be to configure minio without using the included minio in the helm chart.

**Comment by krajorama** [comment]
hi, this is a complicated issue due to opposing requirements and considerations, that we actively talk about, for now we recommend making the copy of the `mimir.config` .

**Comment by krajorama** [comment]
We've decided to implement this together with other features that enable storing the configuration in a configmap.
