### ISSUE TITLE
[mimir-distributed] Allow to disable all optional components

### ISSUE THREAD

**Issue by Skaronator** [grafana/helm-charts#1293]
Currently, it's not possible to disable all optional component in the helm chart. Both, the Overrides-exporter and Ruler cannot be disabled. 

![image](https://user-images.githubusercontent.com/2886913/165113219-d256f726-0369-442b-ab84-e5498bc74704.png)

The alertmanager can be disabled, and the query-scheduler doesn't exist yet.

**Comment by krajorama** [comment]
that's fair, added to backlog
