### ISSUE TITLE
[mimir-distributed] both alertmanager and alertmanager-headless services discovered by the alertmanager ServiceMonitor

### ISSUE THREAD

**Issue by agrahamlincoln** [grafana/helm-charts#1307]
### The Problem

When using the `ServiceMonitor`s generated by mimir-distributed helm chart, alertmanager pods are discovered twice because the labels for `alertmanager` and `alertmanager-headless` services are very similar

This caused the following issue for us:
Using `mimir-mixin` and `mimir-distributed` helm chart together (with prometheus operator ServiceMonitors) causes the `MimirGossipMembersMismatch` alert to fire incorrectly.

### Background/context

The mimir-distributed helm chart can create prometheus-operator ServiceMonitors for prometheus to discover it's components and scrape their metrics.

The mimir-distributed helm chart also creates 2 services for alertmanager, a headless one with no ClusterIP and one with a ClusterIP. When compared to the mimir jsonnet, the [mimir jsonnet only creates a headless service](https://github.com/grafana/mimir/blob/533cef6ef8a564ec3d3c434f0a0a7020c0bcc501/operations/mimir/alertmanager.libsonnet#L90)

The `GossipMembersMismatch` alert in mimir-mixin determines if there is a difference in the number of pods discovered via prometheus (kubernetes service discovery) and the number of members each mimir component expects there to be currently deployed.

When using the mimir-mixin and the mimir-distributed helm chart together, this alert fires because the alertmanager replicas are each discovered twice by prometheus.

**Comment by krajorama** [comment]
Thank you @agrahamlincoln for noticing and providing the fix.
