### ISSUE TITLE
[loki-stack] Promtail v2.4.2 not updated in latest loki-stack chart version.

### ISSUE THREAD

**Issue by wesjdj** [grafana/helm-charts#1316]
The Loki version deployed in version 2.6.4 of the Loki-stack chart is 2.5.0. However, the Promtail version deployed by this chart is 2.4.2, despite the most recent standalone Promtail chart version deploying Promtail version 2.5.0.

**Comment by pierreozoux** [comment]
I'm also looking to have this fixed (with promtail >= 2.5.0):
https://github.com/grafana/loki/commit/8a914b5c2fab45f250a9adc83d32aafcdeebbd30

I try a PR :)

**Comment by zanhsieh** [comment]
Promtail updated. See:
https://github.com/grafana/helm-charts/pull/1692

@wesjdj @pierreozoux 
Feel free to close this issue if feel satisfied.

**Comment by wesjdj** [comment]
This seemed to work, thanks!
