### ISSUE TITLE
Zero Downtime Migration Guide from Old Helm Repository

### ISSUE THREAD

**Issue by Alxander64** [grafana/helm-charts#133]
Wondering if there is any documentation for users who were using the old Helm repositories for things such as Loki
```
https://grafana.github.io/loki/charts
```
and want to move to the new Helm repository is at
```
https://grafana.github.io/helm-charts
```

**Comment by unguiculus** [comment]
As of now, there is no documentation. You just have to update the repo URL. Rendered manifests won't change.
