### ISSUE TITLE
[mimir-distributed] multitenancy and enterprise relationship

### ISSUE THREAD

**Issue by thobianchi** [grafana/helm-charts#1334]
In the default `values.yml` there is the [following](https://github.com/grafana/helm-charts/blob/92d191b7fe298f20b4406e6157530adc9ce87dcf/charts/mimir-distributed/values.yaml#L50) configuration:
```
    {{- if not .Values.enterprise.enabled -}}
    multitenancy_enabled: false
    {{- end }}
```
It is not clear to me if multi-tenancy is a feature available only through an enterprise subscription.  
I am migrating from Cortex and I'm doing some tests in a Kind environment and I see that with that option to true works and enable multi-tenancy but this is legit?  
Is there a list of features available only for enterprise?

**Comment by 56quarters** [comment]
Hello @thobianchi!

Multi-tenancy is available in Mimir and GEM (enterprise), this is a mistake in the chart. GEM has an auth system which Mimir does not but they both support multitenancy. Mimir just requires you supply your own authentication.

**Comment by 09jvilla** [comment]
@56quarters is correct. 

I'm not sure if this is a mistake per se, but maybe we can make this more obvious. It looks to me like Mimir users can specify a configuration via yaml that will override the fact that we set multitenancy to false by default: 

https://github.com/grafana/mimir/blob/116d909b8b85da2774e6e0dcb327473cc52380fd/operations/helm/charts/mimir-distributed/values.yaml#L1357
