### ISSUE TITLE
[mimir-distributed] make minio bucket job naming wrong

### ISSUE THREAD

**Issue by krajorama** [grafana/helm-charts#1345]
E.g. `krajo-mimir-distributed-make-bucket-job-g42xc`  should be just `krajo-mimir-make-bucket-job-g42xc`

Install the mimir-distributed chart and see consistency of pod/job names with `kubectl get pod`

**Comment by 09jvilla** [comment]
@krajorama I don't understand this issue. Let me try...

Are you saying the job that runs `make minio bucket` generates a bucket with the wrong name? What does 'wrong' mean in this context? It seems like the chart works (at least as far as I know) so this 'wrong' name isn't breaking a critical part of the system correct? 

I'm just trying to assess the severity of this bug.

**Comment by Logiraptor** [comment]
@09jvilla The "wrong" name here is the name of the Kubernetes Job object. The Job is ephemeral, so it also doesn't stick around for long. This doesn't impact functionality at all, it's just about having consistency in the naming of resources created by the chart. 

Notice the extra `distributed` in the name of the fourth pod below.
```
$ kubectl get pods
NAME                                             READY   STATUS      RESTARTS   AGE
gem-mimir-smoke-test--1-228v8                    0/1     Completed   0          43h
gem-minio-58f56d5fd8-67smh                       1/1     Running     0          2m38s
gem-mimir-nginx-6ffc647788-rhlpg                 1/1     Running     0          2m38s
gem-mimir-distributed-make-bucket-job--1-d9vfk   0/1     Completed   0          2m38s
gem-mimir-query-frontend-5bcb46ff48-mvzhg        1/1     Running     0          2m38s
gem-mimir-distributor-6b967c5584-kbznn           1/1     Running     0          2m38s
gem-mimir-querier-68d5fdf999-cl8xf               1/1     Running     0          2m38s
gem-mimir-store-gateway-0                        1/1     Running     0          2m38s
gem-mimir-ingester-0                             1/1     Running     0          2m38s
gem-mimir-ingester-1                             1/1     Running     0          2m37s
gem-mimir-ingester-2                             1/1     Running     0          2m37s
```


I think it should be a super easy PR. @aldernero mentioned interest in helping out with Helm. This would be a great issue to start with just to get the development env setup.

**Comment by 09jvilla** [comment]
Ah - thank you for explaining @Logiraptor !

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by 09jvilla** [comment]
@deepto98 - go for it! I don't think @aldernero has picked it up yet and we have plenty of other open issues we can work on.

**Comment by deepto98** [comment]
@09jvilla I think the bucket name is defined here: 
https://github.com/grafana/helm-charts/blob/main/charts/mimir-openshift-experimental/templates/minio/create-bucket-job.yaml?plain=1#L5-L12
Should I replace `name: {{ template "minio.fullname" . }}` with `name: {{ template "minio.name" . }}`?

**Comment by Logiraptor** [comment]
Hi @deepto98, thanks for looking into this. The source code for the mimir helm chart is actually in the main mimir repo now. That file is here for example: https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/minio/create-bucket-job.yaml

I would first try to replace it with the value used in another Job, for example the name from the `smoke-test` job: https://github.com/grafana/mimir/blob/7e4accdb8208dc3f5714cb8f6b7686d16f441773/operations/helm/charts/mimir-distributed/templates/smoke-test/smoke-test-job.yaml#L5

**Comment by deepto98** [comment]
@Logiraptor Thanks for the help, I'll look into.

**Comment by krajorama** [comment]
fixed in https://github.com/grafana/mimir/pull/2427
