### ISSUE TITLE
Version 6.29.0 of the grafana chart has tpl usage problems

### ISSUE THREAD

**Issue by jim-barber-he** [grafana/helm-charts#1350]
While trying to deploy the latest chart it errors with:
```
Error: Failed to render chart: exit status 1: Error: template: grafana/templates/deployment.yaml:49:10: executing "grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: grafana/templates/_pod.tpl:659:20: executing "grafana.pod" at <tpl>: wrong number of args for tpl: want 2 got 1
```

The line in question is:
```
      claimName: {{ tpl (.Values.persistence.existingClaim .) | default (include "grafana.fullname" .) }}
```
And it should be:
```
      claimName: {{ (tpl .Values.persistence.existingClaim .) | default (include "grafana.fullname" .) }}
```

It also looks like line 426 in the same file has a similar problem:
```
        subPath: {{ tpl (.subPath $root) | default "" }}
```
```
        subPath: {{ (tpl .subPath $root) | default "" }}
```

**Comment by jim-barber-he** [comment]
I should add that your GitHub actions picked up the problem too, but I guess the process flow didn't block the breakage from being merged.
https://github.com/grafana/helm-charts/runs/6272415930?check_suite_focus=true

**Comment by Ed87** [comment]
facing the  same issue here

**Comment by outgrow0905** [comment]
facing the same issue here

**Comment by gelicia** [comment]
not a helm expert but if it looks like what OP suggests would work, maybe someone could open a PR?

**Comment by mkenne11** [comment]
I'm also facing the same issue upgrading from grafana 8.4.4 (and the version of the helm chart current at that time).

**Comment by clambin** [comment]
Seems they just released 6.29.1 which changed that code (https://github.com/grafana/helm-charts/pull/1353). But it's still broken.  I have: 

```
    persistence:
      enabled: true
      existingClaim: pvc-grafana
```

But after upgrading to 6.29.1, the resulting deployment is looking for a pvc called "grafana" instead.  Think this line doesn't work as intended:

```
claimName: {{ tpl (default .Values.persistence.existingClaim (include "grafana.fullname" .)) . }}
```

cc [vtavernier](https://github.com/vtavernier), who created that PR.

**Comment by rust84** [comment]
Same issue with 6.29.1.

**Comment by greg-mcnamara** [comment]
Same issue here

**Comment by clambin** [comment]
fixed in 6.29.2.

**Comment by jim-barber-he** [comment]
This is fixed.

**Comment by itsjusth** [comment]
The change on line 426 is causing me a problem
`Error: UPGRADE FAILED: template: grafana/templates/deployment.yaml:49:10: executing "grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: grafana/templates/_pod.tpl:426:25: executing "grafana.pod" at <.subPath>: wrong type for value; expected string; got interface {}`

I do not have any persistent volume claim in my values

**Comment by itsjusth** [comment]
The code change in this issue has caused a new issue:
https://github.com/grafana/helm-charts/issues/1446
