### ISSUE TITLE
[mimir-distributed] Allow mimir.clusterName for metrics to be configured via values

### ISSUE THREAD

**Issue by pdf** [grafana/helm-charts#1387]
#### Description
Currently `mimir.clusterName` relies on `cluster_name` to be present in the generated config, or defaults to `.Release.Name`:

https://github.com/grafana/helm-charts/blob/f2558358b1b4f1c2d9148437716a216ac7c1ad47/charts/mimir-distributed/templates/_helpers.tpl#L240-L245

This strategy has multiple problems:
- In the case that `useExternalConfig` is `true`, the value will always be set to `.Release.Name`, as no config is generated during the Helm run.
- With the default config generator template, `cluster_name` is not output unless enterprise is also enabled (and is not configurable in any case).

Because this value is used to define relabelings on all `ServiceMonitor`s, it will forcably overwrite any `cluster` labels set by the cluster operator.

#### Desired solution
The `clusterName` value should be configurable via helm values, it should default to `.Release.Name` for backwards-compatibility.

**Comment by Fantaztig** [comment]
Another point:

- `cluster_name` cannot be set to true without enterprise (it seems), or the app will report `field cluster_name not found in type mimir.Config`

**Comment by dimitarvdimitrov** [comment]
> Another point:
> 
> * `cluster_name` cannot be set to true without enterprise (it seems), or the app will report `field cluster_name not found in type mimir.Config`

`cluster_name` is a GEM-only config option. It's only used to validate the license GEM is running with. My speculation as to why it's used in service monitors is because the mimir mixin (dashboards, alerts, recording rules) requires that a cluster label exists. So the servicemon's do their best in adding one. 


> Because this value is used to define relabelings on all `ServiceMonitor`s, it will forcably overwrite any `cluster` labels set by the cluster operator.


If we add `honorLabels` in the ServiceMonitor so that existing labels aren't overwritten, will this solve your problem? Or do you still prefer to be able to configure the `clusterName` even for non-enterprise releases?

**Comment by Fantaztig** [comment]
Sounds like the easiest solution to me, I guess the other components (dashboards, alerts) won't have a problem with that as well

**Comment by pdf** [comment]
> If we add `honorLabels` in the ServiceMonitor so that existing labels aren't overwritten, will this solve your problem? Or do you still prefer to be able to configure the `clusterName` even for non-enterprise releases?

Enabling `honorLabels` would cause the job relablings to be ignored also, which would make the resulting metrics incompatible with the monitoring mixin, and the mixin does not provide adequate config options to adjust label matches for this case.

Two options come to mind - allowing `clusterName` to be configured, and providing a default for it that is always set, or providing an option disable relabelling `cluster` in the SM.

I think setting the `clusterName` is probably the right path forward, as it will allow users who have not set a global `cluster` label to use the mixins by default, and also allow for users who wish to provide a specific `cluster` label to set the right value.

**Comment by dimitarvdimitrov** [comment]
You can set your own cluster label by adding a relabeling to `serviceMonitor.rabelings`:

```yaml
serviceMonitor:
  relabelings:
    - targetLabel: cluster
      replacement: foo
```

This makes me inclined to favor the second option: optionally choose to _not_ relabel cluster. Something like `serviceMonitor.keepOriginalClusterLabel: true/false`. I also want to hear what others have to say about this. 

> the mixin does not provide adequate config options to adjust label matches for this case.

I'm not sure what you setup is, but you can open an issue in https://github.com/grafana/mimir/issues and maybe it can be accommodated

**Comment by dimitarvdimitrov** [comment]
yet another option is to save the original `cluster` label to a temporary label `__tmp_original_cluster` so that you can use a relabelling to restore it. I think this is cleaner in terms of adding more config options to the chart.

**Comment by pdf** [comment]
> I'm not sure what you setup is, but you can open an issue in [https://github.com/grafana/mimir/issues](https://github.com/grafana/mimir/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and maybe it can be accommodated

The mixin expects `job` labels in the format `$namespace/$component`, which is fine, as the chart has the corresponding relabelings, however `honorLabels` would break this. The configuration of job labels is already pretty complicated in the mixin, not sure if that's a good place to tackle this or not.

> yet another option is to save the original `cluster` label to a temporary label `__tmp_original_cluster` so that you can use a relabelling to restore it. I think this is cleaner in terms of adding more config options to the chart.

I see where you're coming from - this would not require any additional knobs in the chart, though it would need very clear documentation, as it would be non-obvious otherwise. And though the chart would be cleaner, the deployed resources would be more messy (and cost a couple extra cycles). I'm not entirely opposed to the idea though, as it would provide a solution.
