### ISSUE TITLE
[loki-simple-scalable] Cannot deploy chart 1.0.0 using Azure Storage Account as Storage

### ISSUE THREAD

**Issue by aaron0609** [grafana/helm-charts#1402]
Hi,

We found errors when deploying loki-simple-scalable 1.0.0 using Azure Storage Account:
### Loki-Read:
	kubectl logs loki-read-0 -n blueprint

	level=info ts=2022-05-23T02:53:58.984891402Z caller=main.go:106 msg="Starting Loki" version="(version=2.5.0, branch=HEAD, revision=2d9d0ee23)"
	level=warn ts=2022-05-23T02:53:58.985040703Z caller=experimental.go:20 msg="experimental feature in use" feature="Azure Blob Storage"
	level=error ts=2022-05-23T02:53:58.985158104Z caller=log.go:100 msg="error running loki" err="configdb is not supported as a Loki rules backend type\nerror initialising module: ruler-storage\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:339\nmain.main\n\t/src/loki/cmd/loki/main.go:108\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
### Loki Write:
	kubectl logs loki-write-0 -n blueprint

	level=info ts=2022-05-23T02:53:07.91228964Z caller=main.go:106 msg="Starting Loki" version="(version=2.5.0, branch=HEAD, revision=2d9d0ee23)"
	level=warn ts=2022-05-23T02:53:07.912563142Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache"
	level=warn ts=2022-05-23T02:53:07.912707042Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache"
	level=warn ts=2022-05-23T02:53:07.912794443Z caller=experimental.go:20 msg="experimental feature in use" feature="Azure Blob Storage"
	level=error ts=2022-05-23T02:53:07.912932644Z caller=log.go:100 msg="error running loki" err="mkdir /data: read-only file system\nerror creating index client\ngithub.com/grafana/loki/pkg/storage/chunk/storage.NewStore\n\t/src/loki/pkg/storage/chunk/storage/factory.go:219\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:394\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:106\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:339\nmain.main\n\t/src/loki/cmd/loki/main.go:108\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:339\nmain.main\n\t/src/loki/cmd/loki/main.go:108\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"

### values.yaml configurations:
	loki:
	  config: |
		server:
		  http_listen_port: 3100
		  grpc_listen_port: 9095

		memberlist:
		  join_members:
		  - loki-memberlist

		limits_config:
		  enforce_metric_name: false
		  reject_old_samples: true
		  reject_old_samples_max_age: 168h
		  max_cache_freshness_per_query: 10m
		  split_queries_by_interval: 15m

		schema_config:
		  configs:
		  - from: "2020-12-11"
			store: boltdb-shipper
			object_store: azure
			schema: v11
			index:
			  prefix: index_
			  period: 24h
			chunks:
			  prefix: chunks_
			  period: 24h
		 
		storage_config:
		  azure:
			account_name: lokitest
			account_key: ********
			container_name: loki-logs
			environment: AzureChinaCloud
			request_timeout: 0
		  boltdb_shipper:
			active_index_directory: /data/loki/boltdb-shipper-active
			shared_store: azure
			cache_ttl: 24h
			cache_location: /data/loki/boltdb-shipper-cache
		  filesystem:
			directory: /data/loki/chunks

**Comment by HighWatersDev** [comment]
Running into the same issue

**Comment by LukaszRacon** [comment]
Check where data volume is mounted - try switching `/data` to `/var/loki`:
https://github.com/grafana/loki/issues/6732#issuecomment-1191282217
