### ISSUE TITLE
[loki-distributed] missing metrics endpoint in gateway config

### ISSUE THREAD

**Issue by sureshgoli25** [grafana/helm-charts#1423]
Hi,

We would like to expose the metrics endpoint via gateway.  It seems to be the current gateway configuration have no such option to expose /metrics endpoint.

https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/values.yaml#L752

Kindly let me know how can we expose the metrics endpoints so that, grafana would read from this endpoint.

**Comment by trevorwhitney** [comment]
`cortex-gw` is a closed source component we use at grafana labs for Loki Cloud, so unfortunately that dashboard will not work as is for the helm deployment.

@sureshgoli25 by expose the metrics endpoint via gateway, do you mean for each individual component? What would you propose those routes look like? Also, how would you handle multiple replicas of the same component? Or are you looking to collect metrics about Nginx (the gateway) itself?
