### ISSUE TITLE
[loki-distributed] ingester does not start after upgrade to chart 0.48.4 (can not mkdir /wal, read-only filesystem)

### ISSUE THREAD

**Issue by gebi** [grafana/helm-charts#1444]
Hi,

After upgrading to loki-distributed chart 0.48.4 ignester does not started anymore here because it tries to `mkdir /wal` but can not becuase of a read-only filesystem.

```
level=error ts=2022-06-03T14:50:09.933837597Z caller=log.go:100 msg="error running loki" err="creating WAL folder at \"/wal\": mkdir wal: read-only file system
error initialising module: ingester
github.com/grafana/dskit/modules.(*Manager).initModule
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78
github.com/grafana/loki/pkg/loki.(*Loki).Run
    /src/loki/pkg/loki/loki.go:339
main.main
    /src/loki/cmd/loki/main.go:108
runtime.main
    /usr/local/go/src/runtime/proc.go:255
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1581"
```

I've fixed it with the following config:

```yaml
ingester:
    wal:
        enabled: true
        dir: /var/loki/wal
```

**Comment by trevorwhitney** [comment]
Were you using the default config? Curious because it uses the same [dir](https://github.com/grafana/helm-charts/blob/ef1cd8a48ab000137df980227745d1eeefcfbefb/charts/loki-distributed/values.yaml#L94) you used, and the wal should be enabled by default stating I thin as far back as Loki 2.4

**Comment by gebi** [comment]
ah sry, no i needed to configure a few things and have thus overwritten the config missing the new default setting and forgot to look at the required changes for configs between different loki versions in the upstream repo, sry for the fuss.

**Comment by trevorwhitney** [comment]
no worries. did that fix the issue? can we close?

**Comment by gebi** [comment]
yes, works now, thx for asking, everything fine now :)!
