### ISSUE TITLE
[grafana] Egress for accessing datasources outside namespace

### ISSUE THREAD

**Issue by JWilson45** [grafana/helm-charts#1445]
Hi!
I have Grafana deployed in my instance of Kubernetes and need to access external datasources. Grafana cannot connect to these data sources without a proper egress network policy in place. After inspecting the Network Policy template, it doesn't look like there is support for creating an egress for Grafana, however I could be missing something.

Is there a way to create an egress network policy from the Grafana helm charts?

**Comment by zanhsieh** [comment]
https://github.com/grafana/helm-charts/pull/1496#issuecomment-1155703829
