### ISSUE TITLE
[Grafana] Sidecar dashboards labelValue with unintended behaviour

### ISSUE THREAD

**Issue by monfardineL** [grafana/helm-charts#1457]
Grafana chart version:  6.26.5

When setting sidecar to collect dashboards, according to `README`, the variable `LABEL_VALUE` is not required, but leaving `sidecar.dashboards.labelValue` as `null` causes the value to be set to `1` into Grafana deployment, which breaks the reading of dashboards based on label and without a default value.
![image](https://user-images.githubusercontent.com/9057896/172362156-647eae41-3893-4748-80db-5b16da70aabf.png)

![image](https://user-images.githubusercontent.com/9057896/172362051-12f521a4-8579-4298-9395-13b6c194d184.png)

If I edit the deployment and remove the variable, it starts working normally.

Apparently the code was added into [this](https://github.com/grafana/helm-charts/commit/e28b85231f093d5adf3c4508fe3a452128182990) commit, but I didn't really dig deeper to see if it was different before.
Maybe only including the variable when it's value is different of null could solve the problem.

**Comment by Demonsthere** [comment]
For anyone finding this issue, a simple workaround is to set `labelValue: false`. The problem is that the implementation of `labelValue` in the template is faulty and just checks `if Values.labelValue` instead of checking if it is an empty string

**Comment by zanac1986** [comment]
@Demonsthere @monfardineL 
Please take a look ^^^
