### ISSUE TITLE
[loki-simple-scalable] Cannot connect loki to s3

### ISSUE THREAD

**Issue by 4ns1bl3** [grafana/helm-charts#1458]
Hello,

We are trying to setup loki simple scalable on Kubernetes. The last step we have to do is to connect loki to our buckets in amazon s3. However, the configuration options in the yaml file are not clear since the commit 354995bf213554a9cd1f2152def1ebbd5a8d5bf3 of the loki-simple-scalable/values.yaml file.

There is a new **s3: null** item and we don't know what it does. We also tried to configure the region using the **region** item but the region stays to dummy.

So we have two problems:

- What is the purpose of s3: null 
- How to setup the region of the aws bucket

We are using the latest version (Chart version 1.2.0). Commit hash : b6af1bed803011da47623798a70c111af0d5bc14, date May 24, 2022.

Thanks.

**Comment by quentinbadoud** [comment]
Same problem here.

the reader container says:...  msg="unable to list rules" err="AuthorizationHeaderMalformed: The authorization header is malformed; the region 'dummy' is wrong; expecting 'eu-west-3' ...

Also "region" is not present in the values.yaml from the chart, i just found it on google :)

in the values.yaml:
loki:
  storage:
    bucketNames:
      chunks: loki-chunks2
      ruler: loki-ruler2
      admin: loki-admin2
    type: s3
    s3:
      s3: null
      region: eu-west-3
      endpoint: s3.amazonaws.com
      secretAccessKey: ****
      accessKeyId: *****
      s3ForcePathStyle: false
      insecure: false

**Comment by shyam-ks** [comment]
> Same problem here.
> 
> the reader container says:... msg="unable to list rules" err="AuthorizationHeaderMalformed: The authorization header is malformed; the region 'dummy' is wrong; expecting 'eu-west-3' ...
> 
> Also "region" is not present in the values.yaml from the chart, i just found it on google :)
> 
> in the values.yaml:
> 
> ```
> loki:
>   storage:
>     bucketNames:
>       chunks: loki-chunks2
>       ruler: loki-ruler2
>       admin: loki-admin2
>     type: s3
>     s3:
>       s3: null
>       region: eu-west-3
>       endpoint: s3.amazonaws.com
>       secretAccessKey: ****
>       accessKeyId: *****
>       s3ForcePathStyle: false
>       insecure: false
> ```

Does it work if IAM role with s3 access is attached to ec2 instead of Access keys?
