### ISSUE TITLE
grafana chart - how to add grafana.ini "default" values like app_mode or force_migration

### ISSUE THREAD

**Issue by dominik-ba** [grafana/helm-charts#1464]
The values file provides the possibility to set grafana.ini settings.
The template uses the key for the section `[$key]` and then ranges over the values of that initial key.

Anyhow settings like `app_mode` and `force_migration` are not related to any key. So how can I add this with this helm chart. That's not possible via grafa.ini but only via environment variables, right?

values file:
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L578-L589

configmap template:
https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/configmap.yaml#L16-L28

**Comment by Subetov** [comment]
The same issue.
I'm not able to add ice-monitoring.

**Comment by yegle** [comment]
It looks like you can add to the top level like this: https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L13

**Comment by Subetov** [comment]
@yegle 
Yes, I know. It can't be done by Helm Chart. It's impossible to add any option to root level now.

**Comment by igor-pinchuk** [comment]
Facing this issue as well... so many issues with grafana helm chart...

**Comment by krishnaindani** [comment]
are there anu update to this issue or resulting workaround? We are also facing the same issue on setting `force_migration` field

**Comment by Desolar1um** [comment]
This issue should be closed, as the latest version supports adding `force_migration`
