### ISSUE TITLE
[loki] Standard labels

### ISSUE THREAD

**Issue by blezoray** [grafana/helm-charts#1469]
Hello,

I use the loki helm chart and compare to other loki charts (loki-simple-scalable for example), the loki helm chart doesn't define the standard helm labels, specified here: https://helm.sh/docs/chart_best_practices/labels/

Here is the code of your labels.
https://github.com/grafana/helm-charts/blob/24d178939d7f51c137a2a77b0ee5f00f343ef538/charts/loki/templates/_helpers.tpl#L78

Could you update the labels to be inline with this recommendation ?

Rgds.

**Comment by blezoray** [comment]
Something like this:
```helm
{{/*
Common labels
*/}}
{{- define "loki.labels" -}}
app.kubernetes.io/name: {{ template "loki.name" . }}
helm.sh/chart: {{ include "loki.chart" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
```

**Comment by betorvs** [comment]
And it doesn't allow you to add a custom label. 
Can we have any values config to be able to add a custom label if we want?
