### ISSUE TITLE
Promtail config to exclude namespace is not working 

### ISSUE THREAD

**Issue by claratang98** [grafana/helm-charts#1497]
I am using grafana/loki-stack chart. This is part of my values.yaml file. I am trying to exclude logs collected from any namespace that has "*-system". 
<img width="560" alt="Screenshot 2022-06-15 at 10 35 05 AM" src="https://user-images.githubusercontent.com/90296566/173724462-ceba266d-c04f-467b-a6fd-275b35131caf.png">
The containers keep having crashloopbackoff status and this is the logs from my pod. Is my configurations in values.yaml correct?
<img width="774" alt="Screenshot 2022-06-15 at 10 35 49 AM" src="https://user-images.githubusercontent.com/90296566/173724547-e3f35fce-9685-4b2d-a87e-a87fa0ee62fc.png">

**Comment by mbleichner** [comment]
There seems to be a `:` missing after `relabel_configs`

**Comment by shreymarkandey-srijan** [comment]
after that also its not working for me
still kube-system logs are appearing
