### ISSUE TITLE
`Promtail` - Ability to append `relabel_config` for job with condition

### ISSUE THREAD

**Issue by AmitBenAmi** [grafana/helm-charts#150]
Hello,
I'm using Jsonnet with `promtail` to append `relabel_configs` to the `scrape_config`:

```
promtail_config+:: {
      scrape_configs:
            std.map(
              function(job)
                local k8s_sd_config_with_pod_role = [
                  conf for conf in job.kubernetes_sd_configs
                  if std.objectHas(conf, 'role') && conf.role == 'pod'
                ];
                if std.length(k8s_sd_config_with_pod_role) > 0 then
                  job {
                    prelabel_config+: [
                      {
                        source_labels: ["__meta_kubernetes_namespace"],
                        action: 'drop',
                        regex: 'ingress',
                      }
                    ]
                  }
                else
                  job,
              super.scrape_configs)
    }
```
This way, I'm adding the `relabel_config` to drop `ingress` logs for every job that has the `pod` role.

Using Helm, this isn't possible, since the `scrape_config` is only replaceable or adding extra `scrape_config`, but not appending `relabel_config` with a condition.

Is this possible to implement it or do it somehow, without copy/paste the whole `scrape_config` from the source code and lost the real configuration on updates?

**Comment by denis111** [comment]
I think I have the same problem https://github.com/grafana/helm-charts/issues/220 Just having some extra config before default config instead after would solve the problem. But like you, I don't want copy-paste the whole default scrape config (besides it's templated).

**Comment by AmitBenAmi** [comment]
@denis111 Promtail helm chart version ^3 had some nice adding to this since they added a `tpl` function which helps a lot in terms of copy/paste, which allowed me to reduce the amount of configuration I need to manually override.
Now, I use `promtail.config.snippets.common` in the `values.yaml` and that helped a lot, though it still doesn't give full control over it

**Comment by denis111** [comment]
@AmitBenAmi yes, but you still have to copy-paste the whole default config.snippets.common part, isn't it?...

**Comment by unguiculus** [comment]
@denis111 The chart is already quite flexible. Configuration is already broken down into several snippets, but at some point you have to draw the line. The chart provides a reasonable default config, but for special cases, you just have to roll your own, at least for one of the parts that can be changed. You should probably configure your custom `promtail.config.snippets.common`.

**Comment by unguiculus** [comment]
I assume this can be closed.
