### ISSUE TITLE
[loki-distributed] lastest release did not got released

### ISSUE THREAD

**Issue by nvanheuverzwijn** [grafana/helm-charts#1522]
The latest loki-distributed did not get released. The release workflow failed :
https://github.com/grafana/helm-charts/actions/runs/2492120272

Can we restart this workflow ?

Thank you!

**Comment by zanhsieh** [comment]
Done.
https://github.com/grafana/helm-charts/actions/runs/2492120272

**Comment by nvanheuverzwijn** [comment]
@zanhsieh Seems like because there is no chart changes, it did not re-release the chart. Anyways, we can just wait for the next version I guess but I would have liked 0.48.5 to get the PDB api version fix.

Thanks!
