### ISSUE TITLE
Do not hardcode dependencies in common release workflow

### ISSUE THREAD

**Issue by krajorama** [grafana/helm-charts#1534]
Currently https://github.com/grafana/helm-charts/blob/main/.github/workflows/update-helm-repo.yaml#L131  installs some hardcoded dependencies. The project specific dependency info is in `ct.yaml`  (via `inputs.ct_configfile`) so we should parse and use that.

**Comment by yorugac** [comment]
Hard-coded dependencies also bring out the need to maintain them separately. E.g. the release workflow is not working today [for k6-operator chart](https://github.com/grafana/k6-operator/actions/runs/7127491328/job/19407501991#step:9:30):

![image (1)](https://github.com/grafana/helm-charts/assets/2552297/be12885d-a161-454d-bce7-b8f456e674e9)

Curiously, this chart does not require MinIO in the first place.

**Comment by joeyorlando** [comment]
FYI, this is also breaking the helm release for Grafana OnCall https://github.com/grafana/oncall/issues/3529
