### ISSUE TITLE
grafana chart at 6.32.1 is broken

### ISSUE THREAD

**Issue by Legion2** [grafana/helm-charts#1568]
I updated from `6.32.0` to `6.32.1` and got following error:
`grafana/templates/deployment.yaml:49:10: executing "grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: grafana/templates/_pod.tpl:197:62: executing "grafana.pod" at <len .Values.sidecar.dashboards.labelValue>: error calling len: len of nil pointer`

**Comment by zanac1986** [comment]
@Legion2 
What is your environment set up?

**Comment by KosShutenko** [comment]
I have the same error due update from `6.32.0` to `6.32.1`:

```
Helm upgrade failed: template: grafana/templates/deployment.yaml:49:10: executing "grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: te
mplate: grafana/templates/_pod.tpl:197:62: executing "grafana.pod" at <len .Values.sidecar.dashboards.labelValue>: error calling len: len of nil pointer
```

Sidecar container configured like this:
```
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
      datasources:
        enabled: false
        label: grafana_datasource
```

**Comment by aliusmiles** [comment]
Same here. was able to track this to https://github.com/grafana/helm-charts/pull/1564/files 

`labelValue` for sidecars is set to `null` by default and with that commit it must be set to empty string or some text but not 'true'.

Steps to reproduce:

```sh
helm template grafana grafana/grafana --set sidecar.dashboards.enabled=true --set sidecar.dashboards.labelValue=''
# works
```

```sh
helm template grafana grafana/grafana --set sidecar.dashboards.enabled=true --set sidecar.dashboards.labelValue='true'
Error: template: grafana/templates/deployment.yaml:49:10: executing "grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: grafana/templates/_pod.tpl:197:62: executing "grafana.pod" at <len .Values.sidecar.dashboards.labelValue>: error calling len: len of type bool

Use --debug flag to render out invalid YAML
```

```sh
helm template grafana grafana/grafana --set sidecar.dashboards.enabled=true                                           
Error: template: grafana/templates/deployment.yaml:49:10: executing "grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: grafana/templates/_pod.tpl:197:62: executing "grafana.pod" at <len .Values.sidecar.dashboards.labelValue>: error calling len: len of nil pointer

Use --debug flag to render out invalid YAML
```

Not sure what was intent behind `ne (len .Values.sidecar.datasources.labelValue) 0` but apparently it doesn't work with `null` default value. Perhaps set default labelValue to empty string? I don't quite remember but `if .Values.sidecar.datasources.labelValue` should return False on empty string I think.

**Comment by zanac1986** [comment]
@aliusmiles @KosShutenko @Legion2 
Please check ^^^.

**Comment by llamahunter** [comment]
I think this is similar to https://github.com/prometheus-community/helm-charts/issues/2204

There, when using `grafana.extraConfigmapMounts`, I get the following error.  It's on a different line of `_pod.tpl`, but I suspect it has a similar root problem of dealing with unset optional fields.

```
Error: template: kube-prometheus-stack/charts/grafana/templates/deployment.yaml:49:10: executing 
"kube-prometheus-stack/charts/grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error 
calling include: template: kube-prometheus-stack/charts/grafana/templates/_pod.tpl:426:25: executing
"grafana.pod" at <.subPath>: wrong type for value; expected string; got interface {}
```

**Comment by onedr0p** [comment]
I can also confirm this is a breaking change.

**Comment by zanhsieh** [comment]
This one merged ^^^. Please report if this problem persists. Thank you folks.

**Comment by fwilhelm92** [comment]
> I think this is similar to [prometheus-community/helm-charts#2204](https://github.com/prometheus-community/helm-charts/issues/2204)
> 
> There, when using `grafana.extraConfigmapMounts`, I get the following error. It's on a different line of `_pod.tpl`, but I suspect it has a similar root problem of dealing with unset optional fields.
> 
> ```
> Error: template: kube-prometheus-stack/charts/grafana/templates/deployment.yaml:49:10: executing 
> "kube-prometheus-stack/charts/grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error 
> calling include: template: kube-prometheus-stack/charts/grafana/templates/_pod.tpl:426:25: executing
> "grafana.pod" at <.subPath>: wrong type for value; expected string; got interface {}
> ```

We have the same problem as described in this comment from @llamahunter. However, it can be solved, as already mentioned, by setting the optional fields: 

```yaml
  extraConfigmapMounts:
    - name: <name>
      mountPath: <mount-path>
      configMap: <configmap>
      readOnly: true
      subPath: ''  
```
