### ISSUE TITLE
[tempo-distributed] Service port names cannot be customized

### ISSUE THREAD

**Issue by kmai** [grafana/helm-charts#1570]
I'm using Istio and I cannot change port names to be Istio-compliant.

I know https://github.com/grafana/helm-charts/pull/1021 fixed it for the AIO chart but not for the distributed one :)

**Comment by joe-elliott** [comment]
We would gladly take a PR if you want to try your hand at it. I don't know enough about Istio to suggest a work around (if there is one).

**Comment by zanac1986** [comment]
@kmai 
Could you review this PR ^^^ ?
