### ISSUE TITLE
[loki-distributed] Helm Chart has no option to deploy a query-scheduler for Loki distributed

### ISSUE THREAD

**Issue by sudo6si** [grafana/helm-charts#1574]
Hi,

A separate query scheduler service improves Loki's query performance. Currently, the Helm chart has no option to enable a separate query scheduler. There's a similar issue+PR for [mimir](https://github.com/grafana/mimir/pull/2087) which supports a separate query scheduler.

I would be happy to submit a PR to resolve this issue. But before I begin I wanted to know if this is something that is within the scope of the helm chart for loki-distributed.

Please let me know if it's a yes and I will go ahead with creating the PR and testing it.

Thanks,
-sudo

**Comment by caibirdme** [comment]
Also need query scheduler feature. BTW, I didn't find any examples about how to configure it.

**Comment by salvacorts** [comment]
Closing this one as it has been addressed by https://github.com/grafana/helm-charts/pull/1719
