### ISSUE TITLE
[loki-simple-scalable] dashboard annotations

### ISSUE THREAD

**Issue by jr0dd** [grafana/helm-charts#1607]
The annotations field is present in the values.yaml, but absent in the dashboard templates

**Comment by vkannemacher** [comment]
Hi, I noticed that it is also the case for the labels.

**Comment by zanhsieh** [comment]
@jr0dd @vkannemacher 
Does this PR ^^^ do what you ask for?

**Comment by jr0dd** [comment]
@zanhsieh I forgot about the labels too. Without the proper labels, the grafana sidecar never picks up these dashboards. Need the annotations to specify grafana_folder to organize if running stateless. 

Default from grafana chart. 
```
label: grafana_dashboard
labelValue: ""
```

**Comment by zanhsieh** [comment]
@jr0dd @vkannemacher 
I changed in @zanac1986 branch according to what you asked for, please review and comment on the PR.
