### ISSUE TITLE
grafana chart at 6.32.5 is broken

### ISSUE THREAD

**Issue by Legion2** [grafana/helm-charts#1626]
ef1163293055c47e113f8aec6f022dd232fe0298 introduced log level for sidecar but did use the wrong variable in the helm template `.Values.sidecar.dashboards.logLevel` which does not exist and so the sidecar files to start because empty string is an unknown log level.

**Comment by Legion2** [comment]
@ftpd @zanhsieh you created and merged #1624 which introduced the bug

**Comment by ftpd** [comment]
OMG, so sorry. You're right, I made a mistake and used `.Values.sidecar` in one line and `.Values.sidecar.dashboards` in the other.

@zanhsieh what's the correct way here, should I create the second PR which fixes it?

**Comment by ftpd** [comment]
https://github.com/grafana/helm-charts/pull/1628

**Comment by zanhsieh** [comment]
merged.
