### ISSUE TITLE
[grafana] Should ingress hostname also be set in grafan.ini

### ISSUE THREAD

**Issue by hardillb** [grafana/helm-charts#1685]
At the moment if you set up ingress on the grafana chart and set the hostname you have to repeat the hostname in the `grafana.ini` `server` `domain` to get things to work properly (redirects when adding new charts to dashboards).

The README.md does give a hint to this, but it's implied that it is only needed when looking to run grafana on a subpath rather than at the root of the hostname.

Would you accept a PR to default the `grafana.ini` value to the first entry in the `ingress.hosts` array or if not a README.md update to make it clear you need to set both to make things work properly?

**Comment by zanhsieh** [comment]
@hardillb 
Could you PR this first please? Thank you.
