### ISSUE TITLE
[tempo-distributed]: community users: what is important?  + refactor

### ISSUE THREAD

**Issue by zalegrala** [grafana/helm-charts#1707]
Up to now, the `tempo-distributed` Helm chart has largely been a community effort, which we love.  We really appreciate the contributions we get, in whatever form they take and we want to continue to see them.  Now, I'd like to get some community feedback!

Helm is fast becoming increasingly important to our users as a method to deploy and use Tempo, and Grafana Labs is gearing up to get more involved in at least the Tempo charts, but I suspect some of the other charts as well.  As we get more involved, it starts to make sense for us to align some of our efforts between the databases, and think about how we can simplify and improve long term maintainability.

I'm currently looking at adding Enterprise Traces support to this chart, and in particular and leveraging some patterns that have been added to the `mimir-distributed` chart recently.  Along the way, there are some potentials refactors that I see as opportunity and I'm having a hard time reducing scope of the changes I'd like to make.  So here I'd like to gain an understanding of how folks are using this chart and what is important to keep, and which potentially breaking changes we might include or shy away from.

Part of this comes up because I'd like to import some helpers from Mimir, that may also be shared with Loki.  This would gain us additional consistency across the projects, so some of the renames mentioned below are not just for pseudo-aesthetic reasons, but more around re-use and maintainability.

My initial questions/concerns are as follows:

How important is it to keep the existing labels on the various resources?  If we are internally consistent, is that enough, or are folks relying on these labels for external needs?  Specifically, I'm looking at the label `app.kubernetes.io/name`.  Does renaming from the existing value `tempo-distributed` to a potential new value of `tempo` cause concerns?  Are there other labels that I should be on the lookout for keeping backwards compatibility on?

How important is it to keep the ability to change the image on a per component level?  For example, if we wanted to make a switch between OSS and GET, could we do that in on global place, or are folks tuning the components separately?

Port `:3100` I believe was a copy/paste from the Loki charts, but Tempo has a default HTTP listen port of `3200`.  I suppose this one is a little more touchy since all of the data sources that have been pointed at port `3100` would need to be changed.  What other impacts do we think this might have?

Adding the ability to store the config in a secret may mean adjusting the config resource name.  Given that some of the data in our configuration is sensitive in nature, adding the ability to store this data in a secret seems handy.  This might mean renaming configmaps, or secrets depending on some flags.  Does this cause issues for folks, or is it enough that we are internally consistent?

I think that covers my initial review of looking at the chart the last couple of days.  If there are other items that need to remain backwards compatible, feel free to call them out.  Mentioning a few folks below who I see have worked on this chart recently (in no particular order).

cc: @BitProcessor @jleloup @tete17 @irizzant @rlex @trutty @zanhsieh @zanac1986 @lukas-unity @RomainBelorgey @grafana/tempo

**Comment by rlex** [comment]
Unification of loki, mimir and tempo charts will be great indeed. First thing that comes to mind is different names of gateways in charts - nginx, gateway, nginx-gateway...


> How important is it to keep the existing labels on the various resources? If we are internally consistent, is that enough, or are folks relying on these labels for external needs? Specifically, I'm looking at the label app.kubernetes.io/name

From my side i can say that i rely on them in istio. But changing it from tempo-distributed to tempo should not pose any issues, except probably losing some historical performance data.

> Port :3100 I believe was a copy/paste from the Loki charts, but Tempo has a default HTTP listen port of 3200. I suppose this one is a little more touchy since all of the data sources that have been pointed at port 3100 would need to be changed. What other impacts do we think this might have?

This of course differs from install to install, but i work with tempo via provided nginx-gateway. The only port i call directly from other apps is OTEL sink on distributor from otel-collector.

> Adding the ability to store the config in a secret may mean adjusting the config resource name. Given that some of the data in our configuration is sensitive in nature, adding the ability to store this data in a secret seems handy. This might mean renaming configmaps, or secrets depending on some flags. Does this cause issues for folks, or is it enough that we are internally consistent.

Definitely nice thing to have, personally i use expandenv and store sensitive data in separate secrets, and call them with valueFrom, but if someone is using something like argo with vault plugin, and secrets end up being written in configmap, this is definitely a must.

**Comment by disfluxly** [comment]
I think in general unification is going to be appreciated by the community.

But to explicitly state my thoughts:

1. All breaking changes should be documented. IE - Changing port from 3100 to 3200
2. Any area where you're changing an existing default should be configurable. IE - If people want to continue using `tempo-distributed`, instead of `tempo`, there should be a value that supports this.
3. All deprecations should be clearly stated with the version that they'll be removed from. IE - The config stated in values should continue to exist, with the option of storing it externally in a secret, and if the plan is to remove the in-value config it should be stated that it is deprecated and will be removed in X version.

**Comment by zalegrala** [comment]
Thanks for the feedback folks.  I've put up https://github.com/grafana/helm-charts/pull/1759 to get this started.  I expect to come back and tidy up on a few other things once merged, but I think the PR is a big enough change for now.  Pending review, so let me know if you have concerns about the changes.

**Comment by zalegrala** [comment]
https://github.com/grafana/helm-charts/pull/1759 has been merged for this work.  Thank you for the continued conversation.  The breaking changes have been called out in the changelog as well as the PR, so please have a look.  File issues or PRs for anything I've overlooked, and feel free to ping me about it.
