### ISSUE TITLE
add extra containers in charts/promtail/templates/_pod.tpl

### ISSUE THREAD

**Issue by xiaobin-qmcx** [grafana/helm-charts#1727]
I  deployed the promtail helm chart to upload the logs to loki. However, I can't find any config in charts/promtail/values.yaml which can deploy additional containers. For example, I'd deploy another container which can clean the old logs files.  Can you write some code to support this function in charts/promtail/templates/_pod.tpl  ? Thanks.
Like the code in charts/promtail/templates/_pod.tpl   :
`{{- with .Values.extrContainer }}
   {{- toYaml . | nindent 6 }}
{{- end }}`

**Comment by conorevans** [comment]
This can be closed @xiaobin-qmcx (I forgot to reference properly in #1807)
