### ISSUE TITLE
[loki] Handle PSP alternative with the deprecation in version 1.25 and above.

### ISSUE THREAD

**Issue by d-e-a-n-f** [grafana/helm-charts#1736]
Kubernetes have deprecated PodSecurityPolicy in version 1.25 and above. If support for an alternative policy management is required this could become a spike to evaluate the built in admission controller or evaluate one of the Several external admission controllers are available that incorporate lessons learned from PSP to provide a better user experience. [K-Rail](https://github.com/cruise-automation/k-rail), [Kyverno](https://github.com/kyverno/kyverno/), and [OPA/Gatekeeper](https://github.com/open-policy-agent/gatekeeper/) are all well-known, and each has its fans.

**Comment by zanhsieh** [comment]
https://github.com/grafana/helm-charts/pull/1735
