### ISSUE TITLE
[loki-distributed] fix typo in deployment-compactor.yaml for ports

### ISSUE THREAD

**Issue by khfayzullaev** [grafana/helm-charts#1738]
https://github.com/grafana/helm-charts/blob/b3c0de22803adb4a8629ea20842d2aa8ac4f20ec/charts/loki-distributed/templates/compactor/deployment-compactor.yaml#L65

`ontainerPort` must be `containerPort`

**Comment by rlex** [comment]
how it got merged i wonder, since tests never passed https://github.com/grafana/helm-charts/pull/1390

**Comment by AlphaStyle** [comment]
I apologize, I am the one who managed to add the typo with this [pull request](https://github.com/grafana/helm-charts/pull/1697).

**Comment by zanhsieh** [comment]
https://github.com/grafana/helm-charts/pull/1739
