### ISSUE TITLE
[grafana] alerting provisioning / image renderer - wrong type in template include

### ISSUE THREAD

**Issue by CompuGlobalHyperMegaNet-VP** [grafana/helm-charts#1776]
Hi,

in [this merge](https://github.com/grafana/helm-charts/pull/1720) [this commit](https://github.com/grafana/helm-charts/commit/fa2d1f5f0f5c5c8d089794bdfc6da297c59c171e) changed the code to use templating.

Since that, our helm throws the following error
`error="dry-run upgrade for comparison failed: template: grafana/templates/image-renderer-deployment.yaml:34:28: executing \"grafana/templates/image-renderer-deployment.yaml\" at <include (print $.Template.BasePath \"/configmap.yaml\") .>: error calling include: template: grafana/templates/configmap.yaml:63:7: executing \"grafana/templates/configmap.yaml\" at <$value>: wrong type for value; expected string; got map[string]interface {}"`

The snippet from image-renderer-deployment.yaml:
```  template:
    metadata:
      ....
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```

The diff snippet from configmap.yaml:
```
- {{ toYaml $value | indent 4 }}
+ {{ tpl $value $root | indent 4 }}
```

Is there something we can do do dig deeper into this?

Thanks in advance!

**Comment by CompuGlobalHyperMegaNet-VP** [comment]
@mmusenbr Do you have some input on how to fix this? Thank you!

**Comment by zanhsieh** [comment]
@CompuGlobalHyperMegaNet-VP 
I guess there is `|` missing somewhere.
`toYaml` mostly deals with code like this and format it as yaml:

```yaml
stanza:
  sub_stanza0: aaa
  sub_stanza1: bbb
...
```

whereas the `tpl` simply just take what ever you feed it; does not do extra format. It suppose dealing with code like this:

```yaml
stanza: |
  sub_stanza0: aaa
  sub_stanza1: bbb
...
```
In this case, `tpl` will treat `  sub_stanza0: aaa\n  sub_stanza1: bbb\n ...` as a whole string; whereas `toYaml` will treat it as a `map[string]interface {}`.

**Comment by samortaylor** [comment]
Experiencing this same issue after updating to chart `6.38.3`. 

Wouldn't this follow the same pattern as datasource provisioning? 

`{{ tpl (toYaml $value | indent 4) $root }}`

instead of

`{{ tpl $value $root | indent 4 }}`

**Comment by zanhsieh** [comment]
@samortaylor
Could you PR this?

**Comment by zanhsieh** [comment]
cc [mmusenbr](https://github.com/mmusenbr)
