### ISSUE TITLE
[promtail] 3.0.x features lost

### ISSUE THREAD

**Issue by antonincms** [grafana/helm-charts#186]
I'm surprised of the vanishing of some features in the v3.0.x promtail chart :
* deploymentStrategy that we used to avoid having helm timing out on big clusters
* many clients / server fields are not accessible without customizing the `file` go template.
* extraScrapeConfigs that we used to collect journald logs on kubernetes 

I already reimplemented an extraScrapeConfigs fairly easily by modifying this field, but it makes the values.yaml less readable than I would like. Aren't these not supported anymore by choice, or would it be possible to open PRs to port back these features ?

**Comment by ionutz89** [comment]
I have the same issue with `extraScrapeConfigs`. 
I had fresh deployment via helm and it did not work extraScrapeConfigs feature.

How we should approach with this release ?

**Comment by haghabozorgi** [comment]
@ionutz89 we ended up using something similar to the example https://github.com/grafana/helm-charts/tree/main/charts/promtail#journald-support. basically remove the extrascrapeconfigs and move them under scrape_configs under the config.file section.

**Comment by unguiculus** [comment]
Overall, configurability is way more flexible now. For `extraScrapeConfigs`, there's already a PR (#189), so we should get that back. `deploymentStrategy` was renamed to `updateStrategy` because that's what it actually is. See https://github.com/grafana/helm-charts/blob/main/charts/promtail/templates/daemonset.yaml#L15-L16.

**Comment by antonincms** [comment]
@unguiculus Ok, I see your point, even if I don't really find clean to manipulate the file template (but I guess it will smooth out eventually). 

There used to be the following stage to label all the logs with the labels of their parents pod, is there any reason to not have this anymore ? (If not I will probably open a PR to add this back)
```
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
```

**Comment by unguiculus** [comment]
@antonincms This has been removed on purpose. One should be really careful with labels and not add just blindly add whatever labels there may be. Check out this post: https://grafana.com/blog/2020/08/27/the-concise-guide-to-labels-in-loki/

I you really want all labels, feel free to reconfigure the chart as you like, but adding that back as a default won't be accepted.

**Comment by antonincms** [comment]
Oh, yes I already read this and this make perfect sense, I just did not see that removal from this point of view.
Thank you for your answers @unguiculus !

**Comment by RemiGaudin** [comment]
@unguiculus You said:

> @antonincms This has been removed on purpose. One should be really careful with labels and not add just blindly add whatever labels there may be. Check out this post: https://grafana.com/blog/2020/08/27/the-concise-guide-to-labels-in-loki/
> 
> I you really want all labels, feel free to reconfigure the chart as you like, but adding that back as a default won't be accepted.

But I don't understand how I can restore my labels, I tried to add them manually in the chart like this:

```
config:
  lokiAddress: http://loki.loki:3100/loki/api/v1/push
  snippets:
    pipelineStages:
    - match:
        selector: '{app=~"my_app.*"}'
        stages:
        - docker: {}
        - labels:
            my_label1:
            my_label2:
```
Unfortunately this doesn't work. Please can you give me some indications on how to restore my labels? Many thanks.

**Comment by maver1ck** [comment]
@unguiculus 
Could you please answer to previous question ?
I have the same problem. And I don't see how to get all the labels back.
