### ISSUE TITLE
Referencing invalid service account in tempo-distributed

### ISSUE THREAD

**Issue by lusid** [grafana/helm-charts#1877]
Shouldn't this reference the `tempo.serviceAccountName` as the service account for the ingester?

https://github.com/grafana/helm-charts/blob/76997737b01c1e01850ee57bc648c5e43d249a4f/charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml#L19

**Comment by rbnis** [comment]
Instead of `tempo.serviceAccountName`, this should reference `tempo.ingesterFullname`.
This is the service name, not the serviceAccount name.

I have opened a PR at #1896
