### ISSUE TITLE
explain the purpose of all the helm charts

### ISSUE THREAD

**Issue by githubcdr** [grafana/helm-charts#1887]
So,

In the golden days we had the loki helmchart, and it worked. Now we have 6 different loki charts without anyone telling me why, or what they do. What is loki-stack compared to loki?

As a user, how do I install loki, like in the old days? What chart do I need, where can I read what chart I should use?

Regards and thanks

**Comment by batdevis** [comment]
Very good question @githubcdr, I'm in the same situation.
And it seems that some recipes are depecated and moved to https://github.com/grafana/loki/tree/main/production/helm, but it's not clear.

Maybe the author of [this commit](https://github.com/grafana/loki/pull/6958) @trevorwhitney could enlighten us?

**Comment by alex88** [comment]
> And it seems that some recipes are depecated and moved to https://github.com/grafana/loki/tree/main/production/helm, but it's not clear.

Some are even deprecated on the new one for the old repo 😆

**Comment by trevorwhitney** [comment]
Hi everyone. The problem with the loki helm chart was it was not production ready for large clusters. It ran single-binary, defaulting to local filesystem for storage. The other charts (loki-distributed, loki-simple-scalable) came from the need for more production ready deployments. This, however, created confusion. We are trying to fix that confusion with one chart, now at https://github.com/grafana/loki/tree/main/production/helm, that is production ready by default, but can still be run in the single-binary/local filesystem mode if desired.

If you are going from the old loki helm chart (v2) to the new one (v3), you can follow this guide: https://grafana.com/docs/loki/next/installation/helm/upgrade-from-2.x/

If you are going from loki-distributed to the new one, you can follow this guide: https://grafana.com/docs/loki/next/installation/helm/migrate-from-distributed/

I don't know anything about `loki-stack` or where it came from. I would reach out directly to community members who are active in that chart to find out more about it.

Hope that helps and you don't mind be closing this?
