### ISSUE TITLE
Create a hub on grafana.com for Helm charts

### ISSUE THREAD

**Issue by osg-grafana** [grafana/helm-charts#1904]
See the (internal) design doc at https://docs.google.com/document/d/1hy51hOIfZ_LdEIuPN-QzzHKEHEgX_04fD1qqe3m-3K4/edit#heading=h.5sybau7waq2q. The first Helm chart will be for Mimir, and comes from engineers @krajorama and @dimitarvdimitrov.

https://github.com/grafana/helm-charts/issues/1904#tasklist-block-6b39a6f1-8eb6-4551-8f24-e77ccb70bab5

**Comment by meganmilan** [comment]
For reference, her is the web dev ticket for implementation: https://github.com/grafana/website/issues/10900

**Comment by GrafanaWriter** [comment]
@osg-grafana - I believe this is already in progress, but it's appearing as a new issue, please update. Thanks.

**Comment by osg-grafana** [comment]
The hub is created, and this post-launch issue exists for subsequent work https://github.com/grafana/technical-documentation/issues/544.
