### ISSUE TITLE
[loki-distributed] Affinity value type of compactor is different from that of other components

### ISSUE THREAD

**Issue by kwangil-ha** [grafana/helm-charts#1907]
[compactor]
https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/templates/compactor/deployment-compactor.yaml#L104
`{{- with .Values.compactor.affinity }}`
`affinity:`
`  {{- toYaml . | nindent 8 }}`
`{{- end }}`

[distributor]
https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/templates/distributor/deployment-distributor.yaml#L106
`{{- with .Values.distributor.affinity }}`
`affinity:`
`  {{- tpl . $ | nindent 8 }}`
`{{- end }}`
[ingester]
https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/templates/ingester/statefulset-ingester.yaml#L118
`{{- with .Values.ingester.affinity }}`
`affinity:`
`  {{- tpl . $ | nindent 8 }}`
`{{- end }}`
...

**Comment by verejoel** [comment]
Compactor is meant to be run as a singleton, which could be the reason why this is not configured the same in the chart.

**Comment by kwangil-ha** [comment]
Affinity value type of compactor is yaml, but that of other components is string (with tpl).
I want to set same format. all yaml or all string (with tpl)

**Comment by joscha-alisch** [comment]
Can this be reopened? 
It seems weird to us that for some components, the affinity is configured as an object (querier, compactor) and for others as a string.

**Comment by joscha-alisch** [comment]
Actually, it even seems like the docs are wrong here. The querier component also expects affinity as a string - but the docs say it should be an object.
