### ISSUE TITLE
Tempo distributed chart fails helm template if rbac create set to true

### ISSUE THREAD

**Issue by jlcrow** [grafana/helm-charts#1935]
helm search repo grafana/tempo-distributed                                                                                                                         staging-tools
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                       
grafana/tempo-distributed	0.27.2       	1.5.0      	Grafana Tempo in MicroService mode

`helm template -n tempo tempo grafana/tempo-distributed --set rbac.create=true --debug`

Error: template: tempo-distributed/templates/rolebinding.yaml:8:8: executing "tempo-distributed/templates/rolebinding.yaml" at <include "tempo.labels" .>: error calling include: template: tempo-distributed/templates/_helpers.tpl:69:35: executing "tempo.labels" at <.ctx.Release.Name>: nil pointer evaluating interface {}.Release
helm.go:84: [debug] template: tempo-distributed/templates/rolebinding.yaml:8:8: executing "tempo-distributed/templates/rolebinding.yaml" at <include "tempo.labels" .>: error calling include: template: tempo-distributed/templates/_helpers.tpl:69:35: executing "tempo.labels" at <.ctx.Release.Name>: nil pointer evaluating interface {}.Release

**Comment by zanhsieh** [comment]
@jlcrow 
Shouldn't it be like this?

helm template -n tempo tempo grafana/tempo-distributed --set rbac.create=true --debug

https://github.com/grafana/helm-charts/blob/7ad020dd4e78e177a36dcf398c718f8224d7a545/charts/tempo-distributed/values.yaml#L81

**Comment by jlcrow** [comment]
Why have the flag if it can't be changed to true without crashing the template engine? I was just giving the simplest example, change only that value to true in the values file and it crashes the same way. It didn't in previous versions, because I have it enabled in my deployed chart.

> @jlcrow 
> 
> Shouldn't it be like this?
> 
> 
> 
> helm template -n tempo tempo grafana/tempo-distributed --set rbac.create=true --debug
> 
> 
> 
> https://github.com/grafana/helm-charts/blob/7ad020dd4e78e177a36dcf398c718f8224d7a545/charts/tempo-distributed/values.yaml#L81

**Comment by jlcrow** [comment]
> @jlcrow Shouldn't it be like this?
> 
> helm template -n tempo tempo grafana/tempo-distributed --set rbac.create=true --debug
> 
> https://github.com/grafana/helm-charts/blob/7ad020dd4e78e177a36dcf398c718f8224d7a545/charts/tempo-distributed/values.yaml#L81

My bad I typo'd when I converted the values to a set, I've updated my original post with the error that occurs when you turn rbac.create to true.

**Comment by zanhsieh** [comment]
@zalegrala 
Do you mind to take a look at this?

https://github.com/grafana/helm-charts/blame/085466335efae682ec11f4727f0744efa55a9aa9/charts/tempo-distributed/templates/_helpers.tpl

**Comment by zalegrala** [comment]
Thanks for the report.  I'll take a look this week.
