### ISSUE TITLE
JSON Logs with loki-stack [question]

### ISSUE THREAD

**Issue by eljoth** [grafana/helm-charts#195]
Hey there,
I have deployed loki-stack version 2.3.1 currently scraping the services which omit json structured logs.
When querying `{app="ingress-sync"}|json` for example, no logs are parsed due to a JSONParseErr. I am using the shipped scrapeconfig and the json is correct as can be seen in the following screenshot:
![Bildschirmfoto 2021-01-26 um 17 10 02](https://user-images.githubusercontent.com/21229601/105871401-8ce14100-5ff9-11eb-8f08-bd570eea1a04.png)

Is there anything to set up to be able to parse those logs ?

Thanks in advance!

**Comment by jdub7** [comment]
I'm running into the same issue.  Could be an issue with the CRI pipeline stage, because I don't see stream/output being parsed.

https://grafana.com/docs/loki/latest/clients/promtail/stages/cri/

**Comment by Zeka13** [comment]
works for me out of the box. Make sure you log line is only JSON

**Comment by eljoth** [comment]
I can assure that the logs (including the nginx-ingress-controller) are valid json. I also redeployed the helm chart to three different clusters each with different json-logging services and tried to get the logs parsed without success.

**Comment by Zeka13** [comment]
@eljoth it is veryu wierd, I also use nginx-ingress-controller and can see Parsed Filelds correctly

**Comment by eljoth** [comment]
Unfortunately I cannot see any error messages from loki, why it gave a JSONParserErr. @Zeka13 At first it worked like a charm. But after round about two weeks on the environment it stopped parsing the json logs at all. I can only speculate what it comes from, services haven't changed.
Btw. this is the values-file I am passing for deployment. Are you using any additional config ?
```yaml
loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: managed-premium
    size: 15Gi
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 120h
```

**Comment by Zeka13** [comment]
@eljoth yes and it looks very similar

**Comment by Ognian** [comment]
In my case this was due to the promtail pipeline stage started with `- docker: {}` instead of `- cri: {}`.
I did a very dirty workaround by changing der promtail ConfigMap and replaced blindly `docker: {}`with `cri: {}` 5 times ...
The actual problem is that loki-stack uses totally outdated versions of the referenced charts see #208 and #229.
Hope this will be updated soon...

**Comment by eljoth** [comment]
Thanks @Ognian, I will give that as a workaround. I am replacing the images in my deployment but that doesn't change the loki configuration though.

**Comment by uhthomas** [comment]
Thanks a ton @Ognian 

I found that you can [use both](https://github.com/uhthomas/automata/compare/43dc353..6776df7). All looks good now 😄 

See relevant [docker stage documentation](https://grafana.com/docs/loki/latest/clients/promtail/stages/docker/).

**Comment by chefcook** [comment]
Any news on the initial error from @eljoth.
Facing the same issue  JSONParserErr in Grafana. 

Example log output from Grafana

`2021-06-22T20:35:50.734009632Z stdout F {"msec": "1624394150.733", "connection": "616262", "connection_requests": "13", "pid": "1374", "request_id": "1d2d542bc2db1b0f12401da1403cbe17", "request_length": "41", "remote_addr": "10.240.2.245", "remote_user": "", "remote_port": "60204", "time_local": "22/Jun/2021:20:35:50 +0000", "time_iso8601": "2021-06-22T20:35:50+00:00", "request": "GET /ui/14.js HTTP/2.0", "request_uri": "/ui/14.js", "args": "", "status": "200", "body_bytes_sent": "115582", "bytes_sent": "116550", "http_referer": "", "http_user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36 Edg/91.0.864.48", "http_x_forwarded_for": "", "http_host": "dev.drivelock.cloud", "server_name": "dev.drivelock.cloud", "request_time": "0.253", "upstream": "10.240.1.158:4000", "upstream_connect_time": "0.000", "upstream_header_time": "0.028", "upstream_response_time": "0.256", "upstream_response_length": "115686", "upstream_cache_status": "", "ssl_protocol": "TLSv1.3", "ssl_cipher": "TLS_AES_256_GCM_SHA384", "scheme": "https", "request_method": "GET", "server_protocol": "HTTP/2.0", "pipe": ".", "gzip_ratio": "", "http_cf_ray": "", "geoip_country_code": "" }`

**Comment by chefcook** [comment]
Any updates on the initial issue from @eljoth.

Have the same JSONParserErr issue in Grafana. 
My JSON is valid and I implemented the suggestion from @Ognian.

My thanks in advance!

**Comment by eljoth** [comment]
@chefcook yes @Ognian`s solution worked for me. But it is not satisfying in any ways so I am still watching #208 (and #229)

**Comment by chefcook** [comment]
In case anyone is still interested. You don't have to maintain it manually. I have added the following value to my helm deployment file and the pipelineStages key is correctly provisioned.

```
promtail:
  enabled: true
  nodeSelector:
    kubernetes.io/os = linux
  pipelineStages:
  - cri: {}  
 ```
