### ISSUE TITLE
Tempo retention settable via values file

### ISSUE THREAD

**Issue by nosalan** [grafana/helm-charts#1970]
Tempo values file allows to set `retention` which translates to `compactor.compaction.compacted_block_retention` in the tempo config map.
But this value is not the value that sets how long the traces are kept, it is the length of time a compactor will leave a block in object storage after it has marked it for deletion. It is a low level setting the probably few people needs to configure via values file.
Instead, there is another setting  `compactor.compaction.block_retention` that defines the actual duration to keep blocks. And this is the setting needed to prevent disk from filling up.

I propose to add a setting in values file that controls it, as the existing `retention` needs probably to stay for backward compatibility.
See also this comment: https://github.com/grafana/tempo/issues/1884#issuecomment-1310295822

**Comment by faustodavid** [comment]
Thanks for reporting @nosalan! I will create a PR for the [tempo] chart to use `compactor.compaction.block_retention` like the [tempo-distributed] chart.
