### ISSUE TITLE
[grafana] Can't have persistency with disabled security context

### ISSUE THREAD

**Issue by hoptical** [grafana/helm-charts#2017]
I want to make Grafana persistent by `persistence.enabled: true`. However, I have to disable security context due to the project permissions of my company Openshift cluster: `securityContext: {}` But I face the below error:
```
Error: YAML parse error on grafana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 44: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 44: did not find expected key
```
How can I handle it?

I have made the configurations in `values.yaml`.
Grafana Chart Version: 6.44.8

**Comment by zanhsieh** [comment]
@hoptical 
Just curious, how to simulate OpenShift cluster (3.x or 4.x) locally?

**Comment by hoptical** [comment]
@zanhsieh
I don't know! I'm just using the company OKD cluster.

**Comment by hoptical** [comment]
The problem was solved by setting `initChownData.enabled=false`. The OKD itself will handle the volume permissions.
So, in conclusion, in OKD, you should disable both initChownData and security context.
