### ISSUE TITLE
Why is Grafana exposing on port 80?

### ISSUE THREAD

**Issue by filiprejmus** [grafana/helm-charts#2020]
Hi, sorry my question might sound weird due to my lack of experience. 
I deployed kube-prometheus-stack on a gke cluster the terraform helm provider. Prometheus Grafana Service was deployed to expose port 80 even though kube-prometheus documentation suggests that it should expose port 3000. Port 80 also cannot be port-forwarded as <= 100 ports need sudo access. Now I am wondering if I misunderstood something, as all I actually want to do is to expose the Grafana Service with a LoadBalancer. Help is much appreciated!

**Comment by zanhsieh** [comment]
@filiprejmus
values.yaml is your friend, e.g. service.port .
