### ISSUE TITLE
[loki-stack] PodSecurityPolicy

### ISSUE THREAD

**Issue by ghost** [grafana/helm-charts#2040]
Hello,
i am running a Kubernetes Cluster Version 1.25.3 and wanted to install loki-stack with helm

```bash
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update  
helm upgrade --install loki grafana/loki-stack \
  --debug \
  --namespace loki-stack \
  --create-namespace \
  
[...]
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "loki" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
[...]
```
Now I have two questions

1. (When) Are you planning to remove the PSP (https://kubernetes.io/docs/concepts/security/pod-security-policy/) and implement the new Pod Security Admission (https://kubernetes.io/docs/concepts/security/pod-security-admission/) ?

2. Is there any (easy) way to install and run `loki-stack` on a 1.25.* Cluster ?

Greets

**Comment by martensson** [comment]
I got the same problem running Kubernetes v1.25.4. Not able to install Grafana in my case.

**Comment by zanhsieh** [comment]
@martensson @hannes-unite 
Did you guys upgrade helm to latest? I tried but cannot reproduce the error.

```
$ helm version
version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.19"}

$ helm ls
NAME	NAMESPACE 	REVISION	UPDATED                            	STATUS  	CHART           	APP VERSION
loki	loki-stack	1       	2022-12-06 11:20:24.79084 +0800 +08	deployed	loki-stack-2.8.7	v2.6.1

$ k get po
NAME                  READY   STATUS    RESTARTS   AGE
loki-0                1/1     Running   0          2m12s
loki-promtail-hfh7d   1/1     Running   0          2m12s
```

**Comment by hannes-unite** [comment]
Yes everything is up to date @zanhsieh 
```
$ k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"archive", BuildDate:"2022-11-10T22:18:49Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}
```
Also if i have a look at the grafana repo, i cannot find PodSecurityAdmission, only PSP (https://github.com/grafana/helm-charts/blob/loki-stack-2.8.7/charts/grafana/templates/podsecuritypolicy.yaml), or am i mistaken ?

zansieh can you describe your setup, maybe i can replicate it anyhow ?

**Comment by zanhsieh** [comment]
@hannes-unite 
Due to some complex reasons, we don't implement PSA.

I use Kind to test installation on my MBP m1:

```
$ kind version
kind v0.15.0 go1.19 darwin/arm64
```

**Comment by hannes-unite** [comment]
But how is it possible, that PSP is still in use when kubernetes 1.25 has removed the capability for PSP ?
Did you use a modified kubernetes version ?

**Comment by zanhsieh** [comment]
> But how is it possible, that PSP is still in use when kubernetes 1.25 has removed the capability for PSP ?
> Did you use a modified kubernetes version ?

No, I don't. I suspect it's related to the [test](https://github.com/grafana/helm-charts/tree/main/charts/grafana/templates/tests) due to `grafana-test` in the error message above ^^^ .

**Comment by zanhsieh** [comment]
@hannes-unite 
Could you try this PR #2056 ?

**Comment by ngoyal16** [comment]
Any update on this ?

**Comment by Rohithzr** [comment]
Any update on this?
