### ISSUE TITLE
[loki-distributed] Autoscaler errors on chart update

### ISSUE THREAD

**Issue by M-JobPixel** [grafana/helm-charts#2071]
I'm trying to redeploy the chart with some updated resource limits and requests as, my ingesters seem to be running out of resources now I've got more logs to log from fluentbit.

However when I try and do this I get the following error:

`error: error validating "": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2.ResourceMetricSource]
`
Having a quick look round the internest I found https://www.linen.dev/s/livekit-users/t/2670514/released which seems to be a report of a similar error which was only fixed there 3 days ago.

I assume a similar fix is required on this helm chart.

I'll try and have a look at the chart and see if I can work out what the fix should be, but I'm a relative newbie to the world of helm and fear it will be beyond me.

**Comment by zanhsieh** [comment]
@M-JobPixel 
Might you specify which chart please? grafana/helm-charts hosts more than one chart, such as grafana, loki-stack, etc.

**Comment by mfamador** [comment]
I'm getting that error on `loki-distributed` at least
