### ISSUE TITLE
Using /grafana subpath with Nginx ingress controller does not work

### ISSUE THREAD

**Issue by J-Are** [grafana/helm-charts#2076]
Hi,
I tried to deploy kube-prometheus-stack Helm chart in version **41.7.3** and I would like to expose my Grafana application behind an ingress using subpath /grafana.
I read the Grafana chart readme and Grafana documentation https://grafana.com/tutorials/run-grafana-behind-a-proxy/ but I did not succeed.

The traffic is correctly redirected to my Grafana Kubernetes service but I meet a strange error page:
![image](https://user-images.githubusercontent.com/17073117/208740798-4068cb30-7822-484a-93a6-35302200a97d.png)

This is my values.yaml file I use to deploy my prometheus-stack chart:
```grafana: 
  testFramework:
    enabled: false
  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    hosts:
      - "myhost"
    pathType: Prefix
    path: /grafana
  grafana.ini:
    server:
      domain: "myhost"
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  admin: 
    existingSecret: grafana-admin-credentials
    serviceMonitor:
      enabled: true
    podDisruptionBudget:
      minAvailable: 1
    persistence: 
      enabled: true
      storageClassName: default
alertmanager:
  podDisruptionBudget:
    enabled: true
prometheus:
  podDisruptionBudget:
    enabled: true
  prometheusSpec: 
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: default
          accessModes: ["ReadWriteOnce"]
          resources:
            requests: 
              storage: 50Gi
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
```

I introduced the grafana.ini part from the Grafana chart readme: https://github.com/grafana/helm-charts/tree/main/charts/grafana#example-ingress-with-path

**I have successfuly deploy the prometheus-stack in an older version (32.2.1)**. Grafana is in version **6.21.5**.
I used this configuration with nginx redirection annotations: https://github.com/grafana/helm-charts/tree/main/charts/grafana#how-to-serve-grafana-with-a-path-prefix-grafana. 

I read some documentation and threads on Internet before writting this issue but the root cause does not seem to be clear for me. It sounds to be a bug on Grafana side.

Does anyone has an idea please? 
Thanks in advance for your help

**Comment by jessegoodier** [comment]
is the port standard?
maybe try:
```
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
```

**Comment by batazor** [comment]
I get this error too. I tried to change the domain but it doesn't help me. Grafana worked correctly but after the upgrade k8s cluster, I got this page. I also try to delete/make a new `helm install` but I don't success

**Comment by batazor** [comment]
Maybe problem in grafana -> https://github.com/grafana/grafana/issues/64230
