### ISSUE TITLE
[loki-distributed] ClusterIPs may not change once set

### ISSUE THREAD

**Issue by Siebjee** [grafana/helm-charts#2127]
Since commit https://github.com/grafana/helm-charts/commit/d1ed18ee5d5741d15b78be44477542b8696f3517 the chart updates fail with:

```
warning: Upgrade "loki-distributed" failed: cannot patch "loki-query-frontend" with kind Service: Service "loki-query-frontend" is invalid: spec.clusterIPs[0]: Invalid value: []string{"None"}: may not change once set
```

https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/

Neither was this change conform kubernetes docs.

**Comment by patsevanton** [comment]
How reproduce error? Do you have simple value?

**Comment by Siebjee** [comment]
Just deploy chart version before this change, and deploy the newer version :)

**Comment by patsevanton** [comment]
@Siebjee Are you get error `cannot patch "loki-query-frontend" with kind Service` when upgrade from 0.68.0 to 0.68.1 ?
