### ISSUE TITLE
[tempo-distributed] Add chart for tempo v2

### ISSUE THREAD

**Issue by thomaschaaf** [grafana/helm-charts#2155]
The config of tempo v1 which the chart is generating does not work with tempo v2.
https://github.com/grafana/tempo/releases/tag/v2.0.0-rc.0

**Comment by modulitos** [comment]
I believe this is now resolved, from the PR: https://github.com/grafana/helm-charts/pull/2171

I can confirm that I was able to deploy Tempo 2.0 using the 1.0.0 chart version of tempo-distributed.
