### ISSUE TITLE
Promtail: ability to drop logs based on custom annotation or label.

### ISSUE THREAD

**Issue by denis111** [grafana/helm-charts#220]
Hello, I would like to drop logs from specific set of pods labeled with custom label or annotation for this. The problem is it already has label 'app' and so it will be picked up by default 'kubernetes-pods-app' job and seems like I can't access __meta_kubernetes_pod_annotation_whatever in pipeline_stages so I could just filter it. So is there any way to accomplish it whithout rewriting all default config (config.snippets.common or config.snippets.common.scrapeConfigs)? extraScrapeConfigs is appended at the end, so again, logs would be picked up again by 'kubernetes-pods-app'...

**Comment by unguiculus** [comment]
The chart is already quite flexible. Configuration is already broken down into several snippets, but at some point you have to draw the line. The chart provides a reasonable default config, but for special cases, you just have to roll your own, at least for one of the parts that can be changed. You should probably configure your custom `config.snippets.common`.

**Comment by denis111** [comment]
@unguiculus yes but the default value of config.snippets.common is also quite large to maintain it with copy-paste, maybe it should be empty by default or have some config.snippets.extraCommon?..

**Comment by unguiculus** [comment]
It's always a question how far you want to break down things. That would make the configuration more complicated. Why would empty by default help? You'd always have to roll your own then. As aid, the chart provides a reasonable default that won't work for everyone. Why is it so bad to copy and adapt that for you?
