### ISSUE TITLE
Loki. Ability to update snippets.common

### ISSUE THREAD

**Issue by CrazyTushkan** [grafana/helm-charts#221]
Hello!

I'd like to add some custom labels to pod logs and it seems like `snippets.common` is the best place for them, but I can only override it.
Only way I see how to achieve this is to copy-paste this list entirely, which does not seem correct to me.

It would be nice to have ability to do this.

**Comment by unguiculus** [comment]
I assume you're referring to the Promtail chart. `config.snippets.common` provides a reasonable default. If it doesn't suit your needs, you will have to override it. It is a YAML list which you will always be overwritten completely. You can't get around that limitation. Also, please have a look at `config.snipets.extraScrapeConfigs`. Maybe that helps you.

**Comment by CrazyTushkan** [comment]
Thanks for your response.

Yes I meant promtail, sorry.
Doesn't each element in`extraScrapeConfigs` create new stream?
What I want is extra labels for pod logs you already tracking and overriding what you have already provided just to add few extra labels seems incorrect.
You can get around by adding new list variable (just like `extraScrapeConfigs`) that users can update without duplicating what is already defined by you.

**Comment by unguiculus** [comment]
The chart is already quite flexible. Configuration is already broken down into several snippets, but at some point you have to draw the line. The chart provides a reasonable default config, but for special cases, you just have to roll your own, at least for one of the parts that can be changed. You should probably configure your custom `config.snippets.common`.
