### ISSUE TITLE
Unable to install grafana plugin [grafana-image-renderer]

### ISSUE THREAD

**Issue by AkshayAwate** [grafana/helm-charts#2211]
Hello, i am trying to install [**grafana-image-renderer** ](https://grafana.com/grafana/plugins/grafana-image-renderer/)plugin using helm chart as 
 [using](https://github.com/prometheus-community/helm-charts/issues/444#issuecomment-747576256), but when i add **grafana-image-renderer** as list to plugin its not working. Logs of pods are as below:
 ` level=error msg="Server shutdown" error="*rendering.RenderingService run error: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
*rendering.RenderingService run error: Unrecognized remote plugin message`.  
Good news is i was able to install other plugins like json api. Any help is appreciated!

**Comment by FalconerTC** [comment]
Did you find a resolution here? I'm still seeing this issue

**Comment by Jyoti492** [comment]
@AkshayAwate or @FalconerTC Did you find any resolution for the same . I am facing issue while installing a custom plugin too
