### ISSUE TITLE
gitops, argocd, helm chart deployment, oidc, set roles via groups claim

### ISSUE THREAD

**Issue by lknite** [grafana/helm-charts#2228]
Am successfully deploying grafana using argocd, which can be understood to be a helm chart deployment.

Once deployed I can login as I'm using oidc.  Initially I used 'auto_assign_org_role: Admin', but of course this sets everyone as admin when they login.

I'd like to use the groups passed in via oidc to set the roles.  Am having trouble understanding the documentation and answers posted by others and thought I'd ask to get a better understanding.

It seems to me that I'm supposed to be using:
```
grafana.ini:
  auth.generic_oauth:
    role_attribute_path=contains(info.groups[*], 'grafana-admin') && 'Admin' || contains(info.groups[*], 'grafana-editor') && 'Editor' || 'Viewer'
```

Then, if a user has in its listing of groups 'grafana-admin' it will get the admin role assigned when they login via oidc.  Yet that doesn't seem to be working for me.  Am I understanding the strategy correctly?

**Comment by MrMegaMango** [comment]
is auto_assign_org_role available in helm chart? Everyone in my google auth login as viewer not admin

**Comment by lknite** [comment]
I don't know why this wasn't working for me before, its working great for me now, so closing.

e.g. I'm in 'prod-app-grafana-admin' and this works to map me as an admin in grafana:
```
        role_attribute_path: contains(groups[*], 'platform-readonly') && 'Viewer' || contains(groups[*], 'prod-app-grafana-admin') && 'Admin' || con
tains(groups[*], 'platform-emergency') && 'Admin' || contains(groups[*], 'customer-poweruser') && 'Admin' || contains(groups[*], 'customer-collabora
tor') && 'Editor' || contains(groups[*], 'customer-readonly') && 'Viewer'
```
