### ISSUE TITLE
Promtail needs to support global.imageRegistry and global.imagePullSecrets for private container registries

### ISSUE THREAD

**Issue by johnswarbrick-napier** [grafana/helm-charts#2268]
Promtail cannot be installed from private container registries as it does not support global.imageRegistry and global.imagePullSecrets

This is a problem for air-gapped installations which do not have direct access to the public internet and must use a private, internal container registry.

It also causes a problem when installing Promtail through a parent Helm chart.

Created https://github.com/grafana/helm-charts/pull/2221 which adds this support.

Needs input from a maintainer to review and merge.

**Comment by tynsh** [comment]
This also affects other charts such as grafana itself.

**Comment by zanhsieh** [comment]
#2221 Merged. Close this issue.
