### ISSUE TITLE
[grafana]: Helm chart 6.52.2 is broken when persistence is enabled: unknown field "persistentVolumeReclaimPolicy"

### ISSUE THREAD

**Issue by elwin1234** [grafana/helm-charts#2272]
When installing the latest version of the Grafana Helm chart (`6.52.2`) I get the following error:
```console
foo@bar:~$ helm repo add grafana https://grafana.github.io/helm-charts
foo@bar:~$ helm repo update
foo@bar:~$ helm install grafana-test grafana/grafana --version 6.52.2 --dry-run --set persistence.enabled=true 
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(PersistentVolumeClaim.spec): unknown field "persistentVolumeReclaimPolicy" in io.k8s.api.core.v1.PersistentVolumeClaimSpec
```

This PR seems to be related: https://github.com/grafana/helm-charts/pull/2237

**Comment by zanhsieh** [comment]
@kosta 
Could you take a look at this?

**Comment by kosta** [comment]
Sorry, it seems I screwed up. `persistentVolumeReclaimPolicy` is not a field of [`PersistentVolumeClaim`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#persistentvolumeclaim-v1-core).

There's `persistentVolumeReClaimPolicy` in [`PersistentVolume`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#persistentvolumespec-v1-core) and there's `reclaimPolicy` in [`StorageClass`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#storageclass-v1-storage-k8s-io).

Please revert my PR. Again, I am sorry for this screw-up.

**Comment by zanhsieh** [comment]
Reverted. https://github.com/grafana/helm-charts/pull/2274
