### ISSUE TITLE
cannot specific maxwidht and maxheight of image renderer

### ISSUE THREAD

**Issue by liucy1983** [grafana/helm-charts#2310]
image renderer have maxwidth and maxheight parameter, and default value is 3000.

it only read from config.json in Remote rendering service mode which helm using.

but grafana helm chart does not expose config.json, so i cannot render image large then 3000px, can we add expose image renderer config.json?

**Comment by bradleypettit** [comment]
I believe some of the configurations you mentioned are now exposed as environment variables. In case you still need to modify the config.json, it's now possible to provide your own (https://github.com/grafana/helm-charts/pull/3178).

There's an example in this CI test too https://github.com/grafana/helm-charts/blob/main/charts/grafana/ci/with-image-renderer-values.yaml.
