### ISSUE TITLE
Current grafana sidecar tag fails with secrets

### ISSUE THREAD

**Issue by languitar** [grafana/helm-charts#233]
A few days ago the kiwigrid sidecar version was bumped in the Grafana Chart. This version has a bug that prevents processing secrets instead of configmaps (which was supported before): https://github.com/kiwigrid/k8s-sidecar/issues/110 If possible, the version should be downgraded again until the bug is fixed upstream.

**Comment by monotek** [comment]
New sidcar image was build.
I've added an pr here: https://github.com/grafana/helm-charts/pull/234
