### ISSUE TITLE
Promtail Helm Chart only Creates Service if ServiceMonitor is Enabled

### ISSUE THREAD

**Issue by Alxander64** [grafana/helm-charts#240]
Relevant file can be found here: https://github.com/grafana/helm-charts/blob/main/charts/promtail/templates/service-metrics.yaml

The `Service` is only created if `.Values.serviceMonitor.enabled` is `true`.

I create my own `ServiceMonitor` elsewhere for promtail, and I need just the `Service` created by the chart. I shouldn't have to enable the chart's `ServiceMonitor` just to have the relevant `Service` created with it.

**Comment by unguiculus** [comment]
PRs are welcome.
