### ISSUE TITLE
loki chart 5.5.10 no template loki/templates/configmap.yaml error

### ISSUE THREAD

**Issue by githubcdr** [grafana/helm-charts#2435]
Loki chart upgrade fails since v 5.5.10 with the following error;

> template: loki/templates/single-binary/statefulset.yaml:42:28: executing "loki/templates/single-binary/statefulset.yaml" at <include (print .Template.BasePath "/c │
│ onfigmap.yaml") .>: error calling include: template: no template "loki/templates/configmap.yaml" associated with template "gotpl"

Not aware of any breaking changes, is this a bug?

**Comment by washanhanzi** [comment]
maybe you can refer to [this](https://github.com/grafana/loki/issues/9545)

**Comment by githubcdr** [comment]
Created https://github.com/grafana/loki/pull/9563
