### ISSUE TITLE
loki-distributed helm chart nginx gateway client_max_body_size too small 

### ISSUE THREAD

**Issue by tlaukkan** [grafana/helm-charts#244]
**Is your feature request related to a problem? Please describe.**
loki-distributed helm chart nginx gateway client_max_body_size too small and not configurable except by replacing entire
nginxConfig.

**Describe the solution you'd like**
To be able to configure gateway client_max_body_size in helm values.

**Describe alternatives you've considered**

**Additional context**

**Comment by unguiculus** [comment]
Thanks for reporting this. The Nginx config for the gateway was derived from the Tanka setup for Loki which does not configure client_max_body_size (see https://github.com/grafana/loki/blob/master/production/ksonnet/loki/gateway.libsonnet). You can roll your own Nginx config to fix that. From your experience, is there a value you would recommend? Also, you're always welcome to add the in a PR.

**Comment by nhuray** [comment]
@unguiculus pardon my ignorance but I'm confused by the gateway component on Loki deployment as microservices.
Does the gateway is fronting the distributors or the querier ? 
Considering I already have an nginx ingress fronting my Loki standalone instance, do I need to deploy another nginx gateway if I move to Loki distributed ?

I'm just wondering if the gateway shouldn't be optional and be managed externally, letting people tuning it globally !
