### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by pmacieje** [grafana/helm-charts#2480]
Currently grafana don't start on arm64 nodes. Component download-dashboard got "exec format error" while starting on arm64 arch.

Is there any chance to get arm64 support soon ?

**Comment by zanhsieh** [comment]
@pmacieje 
Did you try specifying `.Values.downloadDashboardsImage.sha` as `90e5dc1fd0c1ea56b5817ea17c8fc82ccb40eaa0e43a336b19a51e30e5b81c41` ? Just curious.
https://github.com/grafana/helm-charts/blob/35f920b1ab963e1c1016205d9628ed6eac57cedb/charts/grafana/values.yaml#L149

**Comment by pmacieje** [comment]
Yeap ... got some old tag in my values for dashboard-downloader. Thanks for your help. :)
