### ISSUE TITLE
Restart grafana service within a container

### ISSUE THREAD

**Issue by Gainutdinov** [grafana/helm-charts#25]
Hello,
Tried to add Zabbix data source by installing related plugin
https://github.com/alexanderzobnin/grafana-zabbix
https://alexanderzobnin.github.io/grafana-zabbix/installation/
so, based on the documentation I need to restart Grafana service but after recreating a container the new data source doesn't appear,
Is there any way to restart Grafana-server without recreating the container?
Additionally, attempted to solve the issue by changing the docker image from alpine to ubuntu one but it didn't help.

Any suggestions ?
Thank you in advance

**Comment by Gainutdinov** [comment]
resolved my issue

**Comment by krtk6160** [comment]
@Gainutdinov Hi, how did you resolve the issue? I am attempting to try somethings similar.

**Comment by Gainutdinov** [comment]
@krtk6160 
Open /etc/grafana/grafana.ini
Go to the [plugins] section
Add allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
