### ISSUE TITLE
[tempo-distributed] Distributors are unable to join cluster ring

### ISSUE THREAD

**Issue by braunsonm** [grafana/helm-charts#2559]
Since the commit made by @zalegrala our clusters are no longer operable on the latest version of the helm chart.

https://github.com/grafana/helm-charts/commit/28e2d47761a3eb7eb8752d4d296721340a1c5f83

Results in the following in all ingestors and distributors failing to join the cluster and rejecting all traces. They log the following repeatedly:
```
level=error ts=2023-07-31T15:37:25 caller=memberlist_client.go:630 msg="failed to resolve members" addrs=dns+tempo-distributed-gossip-ring err="missing port in address given for dns lookup: tempo-distributed-gossip-ring
```

We have reverted our tempo deployments to the old version of the chart (1.4.13) for now and the issue is resolved in that version.

**Comment by 9numbernine9** [comment]
IANA expert, but I think the `join_members` statement needs to include the port number of the service at the end of this line:
https://github.com/grafana/helm-charts/blob/53f6625206f73bfb70436ea84cc6131cf1fb3ef6/charts/tempo-distributed/values.yaml#L1173

**Comment by braunsonm** [comment]
Yep with the port works fine.

**Comment by zalegrala** [comment]
The PR above should resolve this issue.  Thanks for the report.
