### ISSUE TITLE
[tempo-distributed] PDB created with wrong API version

### ISSUE THREAD

**Issue by tjrohweder** [grafana/helm-charts#2564]
**Current behavior**
PodDisruptionBudget requires the api policy/v1 for kubernetes 1.25 or superior, but installing the tempo-distributed helm-chart result in helm trying to create it with policy/1beta1 version in kubernetes

The same type of validation is executed by loki-distributed in the same cluster running Grafana Tempo, but Loki can check the version correctly and it's using the policy/v1 API

**Expected behavior**
Tempo auto detects kubernetes has policy/v1 and use it insted of policy/v1beta1

Kubernetes version: 1.26.6(EKS)

**Comment by Jaspper** [comment]
Same problem faced

**Comment by zanhsieh** [comment]
@Jaspper @tjrohweder 
Can you verify #2644 before I approve and merge please?
