### ISSUE TITLE
[grafana] PDB uses wrong api version

### ISSUE THREAD

**Issue by titirigaiulian** [grafana/helm-charts#2571]
Summary:

After k8s upgrade from 1.24 to 1.25 there are some api deprecations. One such [deprecation](policy/v1beta1: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125) is `PodDisruptionBudget` apiVersion

All across the project, we use `Capabilities` [build it object](https://helm.sh/docs/chart_template_guide/builtin_objects/) from helm.
The problem arrises when trying to install the chart with tools that don't use `helm instal`, but `helm template` and `kubectl apply`. On `helm template` the `Capabilities` feature uses k8s client version which might be different from the remote one.

Possible solution:

Allow `apiVersion` overriding from values.yaml

**Comment by Jaspper** [comment]
Facing the same issue when updating `tempo-distribued` after upgrading k8s from 1.24 to 1.25  
`Error: resource mapping not found for name: "tempo-distributed-ingester" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"`
