### ISSUE TITLE
[lgtm-distributed] Add optional Grafana OnCall to the chart

### ISSUE THREAD

**Issue by timberhill** [grafana/helm-charts#2698]
As suggested in [#1397](https://github.com/grafana/helm-charts/issues/1397#issuecomment-1747289091), it would be useful to add a [Grafana OnCall](https://github.com/grafana/oncall/tree/dev/helm/oncall) to the chart dependencies, but keep it disabled by default. This should be a minor version change.

**Comment by Sheikh-Abubaker** [comment]
@timberhill checkout the PR #3183
