### ISSUE TITLE
extraArgs value bugged in tempo 1.6.1?

### ISSUE THREAD

**Issue by VegardEikenes** [grafana/helm-charts#2705]
I am deploying tempo with the helm chart 1.6.1, and tempo version 2.2.3. I need tempo to access azure for storage, and have therefore configured extraEnv value to point to a secret i created in the same namespace. Since i am using extraEnv, i added extraArgs as well, and my values yaml looks like this:

```
 values:
    tempo:
      repository: xxxxxx
      tag: "2.2.3"
      storage:
        trace:
          backend: azure
          azure:
            container_name: xxxxx
            storage_account_name: xxxxxxx
            storage_account_key: ${AZURE_STORAGE_KEY}
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: AZURE_STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-storage-secret
              key: AZURE_STORAGE_KEY
```

However, when i deploy this helm chart, and the tempo resources are deployed in kubernetes, the arg i added in values looks like this:
"-0=-config.expand-env=true". Somehow, -0= is added to the arg, which is causing the container to crash, since it cant pick up my secret. Why is this being added to the arg?

**Comment by DigiDr** [comment]
I see the same issue on 1.6.3/2.2.3 - how did you fix this @VegardEikenes ?

**Comment by DigiDr** [comment]
Ah, fixed by providing: 

  ```extraArgs:
    "-config.expand-env": "true"```
