### ISSUE TITLE
Mount secret "config-secret" instead of configMap "config"

### ISSUE THREAD

**Issue by YuleZ** [grafana/helm-charts#2734]
I missed to mount secrets created by the changes made in #2663 
I'll fix this as soon as I find some time. You can assign this issue to me.

**Comment by nirmalpathak** [comment]
I configured the alerting to add contact points using `contactpoints.yaml` in the `values.yaml` file but it gives me the following error,
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[1].secret): unknown field "name" in io.k8s.api.core.v1.SecretVolumeSource`

I am using the helm chart version `7.0.11`.

```
$helm upgrade --install my-grafana grafana/grafana --version 7.0.11 -n grafana -f values.yaml
Release "new-grafana" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[1].secret): unknown field "name" in io.k8s.api.core.v1.SecretVolumeSource
```

@YuleZ Is your fix released?

**Comment by YuleZ** [comment]
Fix is here: https://github.com/grafana/helm-charts/pull/2815
