### ISSUE TITLE
Ability to use `envFromSecrets` in Sidecars

### ISSUE THREAD

**Issue by joelp172** [grafana/helm-charts#2808]
When using the Alerts sidecar there is no way to pass in env vars to the container from a secret. 

For example, if a contact-points configmap is deployed to the cluster, within that config map I do not want to hardcode/allow in plain view the Slack Webhook url. If I could pass this in via an env var then I could use the [Environment Variable](https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables) from the container in the contact-points config map

This [PR](https://github.com/grafana/helm-charts/pull/30/files) is an example of the solution required across all the side cars

**Comment by joschahenningsen** [comment]
since #30 is merged, can this be closed? @joelp172
