### ISSUE TITLE
Raw strings (aka passwords) are currently broken in grafana.ini

### ISSUE THREAD

**Issue by nickytd** [grafana/helm-charts#285]
Hi 

in the helm chart before the commit below was possible to have password in [raw string format](https://github.com/grafana/grafana/blob/c40d96d0ab3e7780d9a8c5ef240fb5d9782f1885/conf/defaults.ini#L82)
However with the templating now it is not possible to support this case
https://github.com/grafana/helm-charts/pull/253/commits/a782b2eed96dea4a3aa0910705f338fb6a98b00c

The """#password;""" de facto is rendered with ' suffix and prefix which breaks grafana.ini parsing.

Can you please support the raw strings in grafana.ini template again?

Thanks
Niki

**Comment by jabdoa2** [comment]
Same issue for us. This blocks updates past Chart 6.4.4 for us.
