### ISSUE TITLE
Question: Licensing for Grafana Chart

### ISSUE THREAD

**Issue by geCarlo** [grafana/helm-charts#2882]
What does this license refer to (within the grafana chart.yml)?

"artifacthub.io/license": AGPL-3.0-only

Does this license apply to the grafana helm chart from this project? It seems obvious to me that it does not, given the apache license from the top of the project; however, I am confused by this metadata for this chart.. perhaps it is meant to serve as the most limiting license within the sources, being https://github.com/grafana/grafana?

ref: https://github.com/grafana/helm-charts/blob/adac294d65952e6cfc00d02d9d009f4452adcfae/charts/grafana/Chart.yaml#L13

**Comment by morsik** [comment]
Clear description here: https://artifacthub.io/docs/topics/annotations/helm/

> Use this annotation to indicate the chart’s license. By default, Artifact Hub tries to read the chart’s license from the LICENSE file in the chart, but it’s possible to override or provide it with this annotation

**Comment by rouke-broersma** [comment]
@morsik the license in the repo is apache: https://github.com/grafana/helm-charts?tab=Apache-2.0-1-ov-file#readme
So @geCarlo's question is still valid. Which license applies in this case, the license in the repo or the license set in the annotation in the chart? And is that only true when using the chart through artifacthub, since the annotation is specific to artifacthub?

**Comment by morsik** [comment]
@rouke-broersma oh, that's interesting...

My guess is probably what's in `artifacthub.io/license` applies.

Keep in mind that this repo is not official Grafana Helm Charts. They are *un*official community charts and they were copied from multiple different places, so I don't think they can change licence randomly to Apache 2.0. And yeah... this is quite confusing here... None of the maintainers in helm-charts/charts/grafana/Chart.yaml have `@grafana.com` e-mail so...

And I would say that annotation just gives information to ArtifactHub's internal data, but it should apply everywhere - it still has the same meaning - mention licence for that chart.

**Comment by rouke-broersma** [comment]
@morsik I disagree for two reasons, 1 the license annotation was added by a random contributor and 2 the annotation is metadata specifically for artifacthub and is not part of the official helm chart spec. I would argue that the annotation is most likely wrong and the actual license in the repo covers this chart. If the chart folder had it's own license file I might have agreed with you.

That this repo is unofficial only adds to my belief that the repo license is correct.

**Comment by arukiidou** [comment]
sorry, It seems to have been mistaken for a GRAFANA server.

**Comment by arukiidou** [comment]
- it  fixed in #2909
