### ISSUE TITLE
[Tempo]: Enable Network Policy capability

### ISSUE THREAD

**Issue by hkailantzis** [grafana/helm-charts#2890]
Is hard requirement for us to be able to define Network Policy for Tempo to be able to accept incoming traffic from Grafana or other components like opentelemetry-collector. 
I can deploy manually for now the NP that I need, but would be great to have this option via the values.yaml. This applies to both single binary and distributed.

For Example: https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/networkpolicy.yaml

**Comment by Sheikh-Abubaker** [comment]
@hkailantzis I would like to work on this issue, I went through the example provided above, but I've just started contributing to Open Source and  I'm unable to understand how to enable Enable Network Policy capability for Tempo, are there any resources where I can look into to learn, understand and contribute to this one ? looking forward to learn!!

**Comment by hkailantzis** [comment]
hi @Sheikh-Abubaker, no worries. Is not necessarily Tempo specific, is just Kubernetes related in the end: 
Please find the corresponding values.yaml, for the example above, as they supplement each other: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L1224C1-L1224C14
also official docu on Kubernetes Network policies: 
https://kubernetes.io/docs/concepts/services-networking/network-policies/
Hope it helps!
