### ISSUE TITLE
loki-stack update app version

### ISSUE THREAD

**Issue by renzibin** [grafana/helm-charts#2930]
hi Abubaker
There is an issue with your pull request: https://github.com/grafana/helm-charts/pull/2875,
https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/requirements.yaml#L5
this line version, the mapping version for Loki is v2.6.1, refer to: https://github.com/grafana/helm-charts/blob/loki-2.15.2/charts/loki/Chart.yaml#L4
Therefore, it is not only necessary to change the outer version, but also to change the mapping version of the loki

Best Regards,
Zibin Ren

**Comment by Sheikh-Abubaker** [comment]
@renzibin so you mean that [here](https://github.com/grafana/helm-charts/blob/loki-2.15.2/charts/loki/Chart.yaml#L4) the Loki version should be v2.9.3, and then the subsequent bumped chart version for example v2.16.0 to be mapped [here](https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/requirements.yaml#L5) in order to sync the Loki version across the charts right ?

**Comment by renzibin** [comment]
I'm not sure if version 5.41.8 works because Loki moved the directory, so after you merge it, I'll try to see if I've replaced Loki's version instead of the old version 2.6.1

**Comment by Sheikh-Abubaker** [comment]
> I'm not sure if version 5.41.8 works because Loki moved the directory, so after you merge it, I'll try to see if I've replaced Loki's version instead of the old version 2.6.1

So what do you suggest? To replace Loki's version with the one that still belongs in the directory ?

However I did change the version to 5.41.8 at first to be able to use loki 2.9.3, but then it throws CI lint error of nil pointer interface {}, and when tried to resolve it threw another CI lint error and loki pods doesn't seem to start, you check my first and last commit in the above PR.

**Comment by renzibin** [comment]
https://github.com/grafana/helm-charts/blob/loki-2.15.2/charts/loki/Chart.yaml#L4 
I think this line need to modified to v2.9.3
![image](https://github.com/grafana/helm-charts/assets/52142775/c7bf1471-18cd-4dfa-b883-f37becaf90df)

**Comment by Sheikh-Abubaker** [comment]
I understand your proposed solution but I doubt that it could become confusing for other users as in [artifact hub](https://artifacthub.io/packages/helm/grafana/loki) you can see the loki app version v2.9.3 has chart version v5.41.8, I think maybe we should ask the maintainers for what is needed to be done as of now if they approve of the above changes I would be glad to implement the above.

**Comment by renzibin** [comment]
hi Abubaker
Currently, I am waiting for this solution every day and hope to update the version of loki-stack. Thank you!

Best Regards,
Zibin Ren

**Comment by Sheikh-Abubaker** [comment]
@renzibin As a workaround in your loki-stack values.yaml under loki you can define a image with tag: 2.9.3 as of now while we wait for maintainer's response.

Like this:
```
image:
    tag: 2.9.3
```

**Comment by renzibin** [comment]
@Sheikh-Abubaker 
If only the image label of 2.9.3 is replaced, the installed pod: loki will prompt an error and remain in a pending state. 
error : Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[tmp config storage rules kube-api-access-ttmww]: timed out waiting for the condition

**Comment by renzibin** [comment]
@Sheikh-Abubaker 
I want to confirm, has Loki-stack decided not to maintain it? If not maintained, I can only choose to replace loki-stack with loki

**Comment by Sheikh-Abubaker** [comment]
> I want to confirm, has Loki-stack decided not to maintain it? If not maintained, I can only choose to replace loki-stack with loki

@renzibin 

loki-stack is deprecated though it is not documented yet but you can read this discussion,  the member of Grafana recommended loki over loki-stack.
https://community.grafana.com/t/difference-between-helm-charts-loki-and-loki-stack/87380/2

**Comment by renzibin** [comment]
ok, thanks you for reply. I will use loki replace loki-stack, so i close this ticket,

**Comment by StefanLobbenmeierObjego** [comment]
@renzibin if you find a good migration guide please link it here, I am now also considering moving away from loki-stack

I assume the best solution would be to end up with v3 https://grafana.com/docs/loki/latest/setup/upgrade/upgrade-from-2x/, but not sure if it is possible to do this migration in one step or if it makes sense to first migrate to the non loki-stack v2 and then follow the migration guide to v3

**Comment by StefanLobbenmeierObjego** [comment]
Just looking at how loki-stack works it seems the best solution is to first replace it with all the charts it has as dependencies and then you can follow the normal migration guides for those dependencies.

**Comment by benharosh** [comment]
Can you please add a deprecation note for loki-stack? The above behavior is very confusing (specifying app version v2.9.3 on the chart while actually getting version v2.6.1 from the dependency chart loki-2.15.2 as @renzibin mentioned). On top of all that, you keep bumping versions of loki-stack - so it seems like it's still active and maintained - when there a clear decision to deprecate it.

**Comment by StefanLobbenmeierObjego** [comment]
@fwernert I would not do that, I expect that the helm chart generates a config that is not compatible with later versions of loki, so you would need to use the regular loki helm chart instead.

I followed that migration path:
- for each dependency used in loki stack (e.g. prometheus grafana promtail)
- turn it off in loki stack using `enabled: false`
- add it as the regular helm chart
- eventually loki-stack only deploys loki
- replace that with the latest loki
- you can migrate the data from older loki versions if you really need to, but the easiest way is to run an older loki and a newer loki in parallel until the older lokis data expires, e.g. for us that was two weeks. 
  - If you really need old data you can migrate it, but it requires manually moving its path and telling the new loki instance to use the old schema up to today and start using the new schema from tomorrow onwards
  - (so I think you can see why running loki twice, one active instance, one legacy instance) for a few weeks is the easy way out 😄
