### ISSUE TITLE
Tempo metrics-generator - Add `remote_write_add_org_id_header` config param in the charts

### ISSUE THREAD

**Issue by milon619** [grafana/helm-charts#2954]
The Tempo metrics-generator config parameter `remote_write_add_org_id_header` helps you to configure whether to add X-Scope-OrgID header in remote write requests. It would be nice to have this available in the `tempo-distributed` charts. A specific use-case would be to set a dedicated tenant while remote-writing the span metrics exported by metrics-generator component. Currently even if we configure the tenant explicitly in the remote-write settings it's overwritten by the tenant info from the trace data.

Ref: https://github.com/grafana/tempo/issues/1448

**Comment by Sheikh-Abubaker** [comment]
@LinTechSo @milon619 checkout the PR(https://github.com/grafana/helm-charts/pull/3173).

**Comment by Sheikh-Abubaker** [comment]
You're welcome @milon619 🤝
