### ISSUE TITLE
[Pyroscope] Error installing Pyroscope using Helm in micro-service way

### ISSUE THREAD

**Issue by jmtt89** [grafana/helm-charts#2960]
follow the installation guide using helm -> https://grafana.com/docs/pyroscope/latest/deploy-kubernetes/helm/

using `Option B: Install Pyroscope as micro-services. In this mode, as you scale out the number of instances, they will share a singular backend for storage and querying.`

```
$ helm upgrade --install -f values-micro-services.yaml pyroscope grafana/pyroscope --namespace pyroscope
Release "pyroscope" does not exist. Installing it now.
Error: template: pyroscope/templates/deployments-statefulsets.yaml:100:70: executing "pyroscope/templates/deployments-statefulsets.yaml" at <$values.readinessProbe>: wrong type for value; expected map[string]interface {}; got interface {}
```

i try to delete readinessProbe section on store-gateway but the error continue, looks like a problem with the helm chart.

**Comment by jmtt89** [comment]
debugging the template, the problem is 

`(hasKey $values.readinessProbe "initialDelaySeconds")` 

changing in `deployments-sataatefulsets.yaml`

```
          {{- if and (hasKey $values "readinessProbe") (hasKey $values.readinessProbe "initialDelaySeconds") }}
            initialDelaySeconds: {{ $values.readinessProbe.initialDelaySeconds }}
          {{- end }}
```

by

```
          {{- if (($values.readinessProbe).initialDelaySeconds) }}
            initialDelaySeconds: {{ $values.readinessProbe.initialDelaySeconds }}
          {{- end }}
```

fix the problem

**Comment by simonswine** [comment]
@jmtt89 let's centralise debugging on this issue: 

https://github.com/grafana/pyroscope/issues/3004
