### ISSUE TITLE
[grafana] Service account automountServiceAccountToken should be set to false

### ISSUE THREAD

**Issue by alita1991** [grafana/helm-charts#2976]
Disabling automatic token mounting with automountServiceAccountToken set to false enhances security and control in Kubernetes by reducing attack surface, providing explicit control over token usage, avoiding unnecessary access, and meeting compliance and security requirements.

While looking at the grafana service, I noticed that the automountServiceAccountToken flag is set to true and I'm trying to understand if there is a reason for this, if not, I'm interested in setting the flag to false.

**Comment by haraldkoch** [comment]
>  I noticed that the automountServiceAccountToken flag is set to true and I'm trying to understand if there is a reason for this

  I guess we have the answer now - yes.
