### ISSUE TITLE
Grafana chart version `7.3.2` breaks k8s-sidecar

### ISSUE THREAD

**Issue by onedr0p** [grafana/helm-charts#2986]
Discussed here 

https://github.com/grafana/helm-charts/pull/2977

**Comment by webwurst** [comment]
Thanks for pointing out, got quite confused by this..

**Comment by Sheikh-Abubaker** [comment]
@onedr0p 

please checkout the revert PR.

**Comment by dmaclaury** [comment]
For anyone else who stumbles into this issue after upgrading, setting `serviceAccount.autoMount=true` in your values will avoid the breakage. 

The chart's readme values table did not get updated to capture the change of default values in #2977
