### ISSUE TITLE
renovatebot

### ISSUE THREAD

**Issue by venkatamutyala** [grafana/helm-charts#3067]
Any thoughts on adding renovate bot? it's pretty trivial to install and in this repo i imagine it would help greatly in keeping the various helm charts up to date when new releases/docker tags are dropped.

https://github.com/apps/renovate

I have a config file I'd be happy to share

**Comment by Footur** [comment]
See #2611

**Comment by venkatamutyala** [comment]
Thanks @Footur I should have checked more closely on existing issues.
