### ISSUE TITLE
[loki-distributed] gateway location overrides in multi tenant setup

### ISSUE THREAD

**Issue by ubergesundheit** [grafana/helm-charts#312]
Right now one can override the gateway nginx configuration using the `gateway.nginxConfig`. I have a custom setup where I added a deployment of [loki-multi-tenant-proxy](https://github.com/k8spin/loki-multi-tenant-proxy which I want to use instead of the authentication that one can configure through `gateway.basicAuth` or ingress configuration.

In my case I need to override the whole of the [`gateway.nginxConfig` key[(https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/values.yaml#L597-L664) to just change a few lines. To be specific, the `proxy_pass` lines.

@unguiculus would you be interested in a PR which would allow users to change the ports and hostnames in the `proxy_pass` lines for the `distributor`, `querier` and `queryFrontend` targets.

The PR changes could look like this. I hope you get the idea.

```diff
....

# Configuration for the gateway
gateway:
...
+ distributorLocationTarget: "http://{{ include "loki.distributorFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri" 
+ querierLocationTarget: "http://{{ include "loki.querierFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri"
+ queryFrontendLocationTarget: "http://{{ include "loki.queryFrontendFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri"
  # -- Config file contents for Nginx. Passed through the `tpl` function to allow templating
  # @default -- See values.yaml
  nginxConfig: |
    ...

        location = /api/prom/push {
-         proxy_pass       http://{{ include "loki.distributorFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
+         proxy_pass       {{ .Values.gateway.distributorLocationTarget }};
        }

        location = /api/prom/tail {
-         proxy_pass       http://{{ include "loki.querierFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
+         proxy_pass       {{ .Values.gateway.querierLocationTarget }};
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }

        location ~ /api/prom/.* {
-         proxy_pass       http://{{ include "loki.queryFrontendFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
+         proxy_pass       {{ .Values.gateway.queryFrontendLocationTarget }};
        }

...
```

**Comment by unguiculus** [comment]
I'm torn on that one. This is a really specific use case. I'd probably be better to just roll your own NGINX config. In your case, you ideally shouldn't need the gateway at all and the proxy you mention should handle that directly. Not sure if that is possible.

**Comment by ubergesundheit** [comment]
This is an use case for people using the loki multi tenant mode where tenants are differentiated by a `X-Org-id` header. Do you know if grafana will provide something to validate credentials against this org-id header?

**Comment by unguiculus** [comment]
I agree, it's a use case if you have untrusted tenants. You should ask your question in Grafana's community forum or on Grafana Slack. I don't know the answer.

**Comment by ubergesundheit** [comment]
Thanks :)
