### ISSUE TITLE
[grafana] cannot import a dashboard with multiple datasources from grafana.com

### ISSUE THREAD

**Issue by TagadaPoe** [grafana/helm-charts#313]
The following code is the section of the bash script that downloads a dashboard from Grafana:
```
    {{- if $value.url -}}"{{ $value.url }}"{{- else -}}"https://grafana.com/api/dashboards/{{ $value.gnetId }}/revisions/{{- if $value.revision -}}{{ $value.revision }}{{- else -}}1{{- end -}}/download"{{- end -}}{{ if $value.datasource }} | sed '/-- .* --/! s/"datasource":.*,/"datasource": "{{ $value.datasource }}",/g'{{ end }}{{- if $value.b64content -}} | base64 -d {{- end -}} \
    > "/var/lib/grafana/dashboards/{{ $provider }}/{{ $key }}.json"
      {{- end -}}
    {{- end }}
```
The sed command replaces ALL datasources with the single datasource provided in values, if present.

**Expected behaviour**

We should be able to specify multiple datasources in the chart values and replace each datasource with the right datasource.

If the dashboard was exported with the "external" checkbox enabled, then we sould be able to replace the datasource based on the variable name (e.g, replace "${DS_PROMETHEUS}" by the actual datasource name).

**Comment by lemaral** [comment]
For example the Loki quick search dashboard cannot be imported correctly: https://grafana.com/grafana/dashboards/12019

**Comment by kodeine** [comment]
Any updates on this?

**Comment by FrankGiesecke** [comment]
Did anyone found a solution for this problem?
I run the the same problem like @lemaral with https://grafana.com/grafana/dashboards/12019

**Comment by igor-pinchuk** [comment]
It is not clear how one should be importing any of the dashboards that have multiple data sources.
In my case these two dashboards:
https://grafana.com/grafana/dashboards/14055
https://grafana.com/grafana/dashboards/12019

Probably there are many more dashboards that have more than one data source.

In the helm chart values we can provide only one data source, e.g:
```
loki-stack-monitoring:
    gnetId: 14055
    datasource: Prometheus
```

This bug makes many dashboards incompatible with projects that use grafana chart as a dependency (kube-prometheus-stack in my case).

It is very strange that issue like this (which was reported more than a year ago) still has not attracted any attention from maintainers and there are very few people interested in it... probably nobody uses grafana in combination with Loki...
