### ISSUE TITLE
[chart/loki-distributed] Request to have separate service account for `Ingester` and `Compactor`

### ISSUE THREAD

**Issue by petersin0422** [grafana/helm-charts#320]
The chart currently only supports attaching one service account to all components of Loki. We are using AWS IRSA to map a service account to an IAM role to grant `ingester` and `compactor` access to the chunk store. However, the other components don't really require access to the store, in order to be compliant with the best practice of least privilege, do you think it would be a good idea to have separate service accounts for `ingester` and `compactor`? Thank you very much!

**Comment by unguiculus** [comment]
`querier`, `table-manager`, and `ruler` need access to the store, too. I wonder if it is really worth the effort then. It would make the chart quite a bit more complicated.

**Comment by petersin0422** [comment]
Make sense, maybe not. Thank you very much for your reply!
