### ISSUE TITLE
[tempo-distributed] Recommended replicas/quorum 

### ISSUE THREAD

**Issue by adamstrawson** [grafana/helm-charts#326]
Sorry if this isn't the correct platform for an implementation question. 

With the `tempo-distributed` chart, the default replicas for all services is `1`. Is this the recommended number or do some services require some form of quorum?

I ask as I've found that if running with single replicas, and a pod restarts (for example, `ingester`), other services then fail to operate until they too have been restarted, so my assumption is it's better practice to run a replica of 2 or above for some services?

Here's an example (all pods are up and in a `ready` state)

Logs from `tempo-querier`

```
level=error ts=2021-03-18T19:33:48.934790097Z caller=frontend_processor.go:53 msg="error contacting frontend" address=172.20.255.236:9095 err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.20.255.236:9095: connect: connection refused\""
level=warn ts=2021-03-18T19:34:29.645467577Z caller=logging.go:71 traceID=1013227ae3d723d8 msg="GET /querier/api/traces/...(500) 82.845µs Response: \"error finding ingesters in Querier.FindTraceByID: at least 1 live replicas required, could only find 0\\n\" ws: false
```

The above indicates it's attempting to connect to a pod that no longer exists (pod ip/port is no longer valid) as the ingester had been restarted prior.

After terminating the querier pod, it'll start up and work as expected as it will then find the correct ingester.

**Comment by adamstrawson** [comment]
@joe-elliott Maybe one for you?

**Comment by joe-elliott** [comment]
The only piece of Tempo that has quorum-like behavior are the ingesters.  The helm chart defaults to RF1 so 1 ingester is fine. RF1 is ok for a lot of applications (although rollouts will cause refused batches), but if you need guarantees about read/write behavior then you need to use RF3 and then, yes, you will need at least 3 ingesters.

We also experimented with RF2 for awhile.  There is, in fact, some custom code in Tempo to handle RF2. It does not have real read/write guarantees, but it actually worked quite well for a long time internally. B/c I never felt like it was delivering the guarantees that I wanted to do my internal teams I eventually switched to RF3.

**Comment by adamstrawson** [comment]
Thanks @joe-elliott Useful to know, and answers my question! Enjoy your weekend!
