### ISSUE TITLE
[grafana] Unable to Merge PRs

### ISSUE THREAD

**Issue by Xtigyro** [grafana/helm-charts#330]
Hey guys - even though the `CODEOWNERS` file is correct, me and @rtluckie are not picked up as potential approvers upon the creation of a new PR and also we cannot merge any approved PRs.

Is there setting of GitHub org that needs to be tweaked or is it related to the `@grafana/helm-charts-admins` we are not part of?

A good example right now is: https://github.com/grafana/helm-charts/pull/329

**Comment by Xtigyro** [comment]
Hey @unguiculus 👋 

Do you know whether there's actually an existing `@grafana/helm-charts-admins` in the `grafana` GitHub org? I suspect that might be the problem.

**Comment by unguiculus** [comment]
I don't know. I'm not an admin either. It's not required to be admin in order to be able to merge. 

@torstenwalter Could you have a look, please?

**Comment by torstenwalter** [comment]
Should be fixed now. I changed your permissions. 
@rtluckie has an outstanding invitation to this repository which he need to accept.

**Comment by Xtigyro** [comment]
@unguiculus @torstenwalter Thank you, guys! ⛵ Will test it soon here: https://github.com/grafana/helm-charts/pull/341

**Comment by Xtigyro** [comment]
@unguiculus @torstenwalter Thank you - works perfectly! 🥇
