### ISSUE TITLE
tempo compactor extraEnv missing

### ISSUE THREAD

**Issue by peetasan** [grafana/helm-charts#3341]
[Line 73](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/compactor/deployment-compactor.yaml#L73) should be extraEnv instead of env as envs are not generated like this. This was introuduced in https://github.com/grafana/helm-charts/pull/3333/files

**Comment by msvechla** [comment]
I also noticed this, I opened a fix PR here: https://github.com/grafana/helm-charts/pull/3345
