### ISSUE TITLE
envFromSecrets is broken

### ISSUE THREAD

**Issue by realkarmakun** [grafana/helm-charts#3370]
Attempting to install latest version of Grafana Helm chart is impossible if using `envFromSecrets`, which suppose to be a list of secrets with env variables to pass secrets and such securely.

```
helm install grafana grafana/grafana -n grafana -f values.yaml
Error: INSTALLATION FAILED: template: grafana/templates/deployment.yaml:52:10: executing "grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: grafana/templates/_pod.tpl:1095:23: executing "grafana.pod" at <.name>: can't evaluate field name in type interface {}
```

Passing it like so:
```yaml
envFromSecrets:
  - grafana-pgsql
  - grafana-oidc
```

Removing `envFromSecrets` results in successful installation (of course without any secrets)

**Comment by Adrian43211234** [comment]
Hello @realkarmakun 

stumbled over your issue because I was using `envFromSecret` for multiple secrets instead of `envFromSecrets`

However you are missing the `name` in the config:

```
    envFromSecrets:
      - name: grafana-pgsql
      - name: grafana-oidc
```

**Comment by realkarmakun** [comment]
Oh I didn't know that. Helm chatr values are rather obscure. Thanks. I'll close the issue then
