### ISSUE TITLE
bump Grafana version in loki-stack Helm chart from 6.7.0 to 7.x.x

### ISSUE THREAD

**Issue by zuchka** [grafana/helm-charts#363]
The loki-stack Helm chart is currently configured to provision Grafana 6.7.0. This issue suggests bumping the version to 7.x.x.

https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml

Bumping to 7.5.2 would then match the current version in the standalone Grafana Helm chart.

**Comment by masterkain** [comment]
yes please

**Comment by mxsxs2** [comment]
I am wondering if there are compatibility issues with the rest of the dependencies or is it just a matter of bumping it?

**Comment by tylerbartlett** [comment]
waiting on this too

**Comment by zuchka** [comment]
looks like the chart got bumped to 7.5.0
