### ISSUE TITLE
Add a default index page to the `gh-pages` branch

### ISSUE THREAD

**Issue by sakjur** [grafana/helm-charts#37]
JFrog's Artifactory seems to have problems handling Helm repos without a default index page, which is being tracked by upstream in [RTFACT-21534](https://www.jfrog.com/jira/projects/RTFACT/issues/RTFACT-21534?filter=allopenissues). I think that adding an empty `index.html` file to the `gh-pages` branch might fix it before upstream has fixed it (+ a blank page might be better/less confusing than a 404)

For more information, refer to [Slack conversation](https://grafana.slack.com/archives/C05675Y4F/p1601564001095100) ([copy of Slack conversation](https://github.com/grafana/helm-charts/files/5313096/artifactory.log))

**Comment by torstenwalter** [comment]
@sakjur could you test if https://charts.jenkins.io/ works with Artifacoty? In that case #38 would fix your issue.

**Comment by PhamJay** [comment]
@torstenwalter I just tested adding https://charts.jenkins.io/ as a remote repository to Artifactory v6.16.0. It seems to be working.
