### ISSUE TITLE
Update grafana helm chart to use grafana app 7.5.5

### ISSUE THREAD

**Issue by llamahunter** [grafana/helm-charts#412]
There are some issues with cookie clearing in grafana < 7.5.5 (see https://github.com/grafana/grafana/issues/15316). Potentially this was fixed in https://github.com/grafana/grafana/pull/32999, which was cherrypicked into the 7.5.5 release https://github.com/grafana/grafana/pull/33136, and released https://github.com/grafana/grafana/releases/tag/v7.5.5.

It would be helpful to update this chart to pick up the change, so that it can be picked up by downstream charts like kube-prometheus-stack which reference grafana chart versions 6.8.* (https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-15.2.2/charts/kube-prometheus-stack/Chart.yaml#L47)

**Comment by zanhsieh** [comment]
@llamahunter 
Could you PR it please?

**Comment by llamahunter** [comment]
fixed by https://github.com/grafana/helm-charts/pull/419
