### ISSUE TITLE
[Grafana Chart] How to change service type to NodePort

### ISSUE THREAD

**Issue by kaykhancheckpoint** [grafana/helm-charts#413]
Hi friends is there a way to change the service node type to be NodePort. 

Ive tried just changing this field https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L129 to be `NodePort` but then the service never spawns on my k8s cluster.

**Comment by anon6789** [comment]
Hey @kaykhancheckpoint 

The service type can be changed using the value `service.type`.

I created a short example by just setting this single value on command line. I checked the `helm template` output first:

```
$ helm template grafana/grafana --set "service.type=NodePort"
[...]
---
# Source: grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-grafana
  namespace: default
  labels:
    helm.sh/chart: grafana-6.9.1
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "7.5.5"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000

  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: RELEASE-NAME
[...]
```
The `type` looks fine, so I continued to install it to my cluster:

```
$ helm install my-release grafana/grafana --set "service.type=NodePort"
```

and checked the Kubernetes service object:
```
$ kubectl get service
NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
kubernetes           ClusterIP   10.120.0.1     <none>        443/TCP        29m
my-release-grafana   NodePort    10.120.3.107   <none>        80:32356/TCP   16s
```

So this works on my side by setting `service.type=NodePort`.

Make sure to check if you use multiple values files which may overwrite each other. You could try to set the value using the `--set` command, which overwrites all previous values for this field.
Furthermore I would check if `service.enabled` is set to `true`. You mentioned that the service is not present in your cluster.
So maybe try the following values file:
```
service:
  enabled: true
  type: NodePort

```
