### ISSUE TITLE
[Grafana] PodSecurityPolicy not set correctly for init-Container

### ISSUE THREAD

**Issue by modzilla99** [grafana/helm-charts#427]
Since I already opened a bug on the prometheus-stack chart, which directly uses the grafana chart I might as well use the info provided there:

Describe the bug
When I deploy the prometheus-stack with persistent storage for prometheus and grafana it will always get stuck with the errormessage "unable to admit pod: [spec.initContainers[0].securityContext.runAsNonRoot". The grafana pod can't create the init container and therefore doesn't run.

Version of Helm and Kubernetes:

Helm Version:

$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

Kubernetes Version:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:20:25Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

Which chart:
kube-prometheus-stack
Which version of the chart:
15.4.4
What happened:
unable to admit pod: [spec.initContainers[0].securityContext.runAsNonRoot
What you expected to happen:
Addition of a different servicaccount for grafana with a PSP that allows root access or privilege escalation, so that the init container can do its chowning
How to reproduce it (as minimally and precisely as possible):
Enable PodSecurityPolicy on the cluster and deploy the chart.
Changed values of values.yaml (only put values which differ from the defaults):

values.yaml

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
grafana:
  rbac:
    pspEnabled: true
  adminPassword: 2d13e45a3ad3b77ec9aec7
  persistence:
    type: pvc
    enabled: true
    accessModes:
      - ReadWriteMany
    size: 20Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection

The helm command that you execute and failing/misfunctioning:

For example:

$ helm install --repo https://prometheus-community.github.io/helm-charts --version 15.4.4 prometheus kube-prometheus-stack --values values.yml

Helm values set after installation/upgrade:

$ helm get values prometheus
USER-SUPPLIED VALUES:
grafana:
  adminPassword: 2d13e45a3ad3b77ec9aec7
  persistence:
    accessModes:
    - ReadWriteMany
    enabled: true
    finalizers:
    - kubernetes.io/pvc-protection
    size: 20Gi
    storageClassName: longhorn-rep1
    type: pvc
  rbac:
    pspEnabled: true
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: longhorn-rep1

Anything else we need to know:

To work around the issue I changed the entry MustRunAsNonRoot to RunAsAny with kubectl edit psp prometheus-grafana

...
  runAsUser:
    rule: RunAsAny
...

**Comment by modzilla99** [comment]
#261

**Comment by devopstales** [comment]
And add this config to the values.yaml
```
initChownData:
  enabled: false
```

**Comment by kravvcu** [comment]
To elaborate on @devopstales answer as to why that works: the chown init container performs a recursive `chown` (surprise surprise ;)) on grafana's data dir (/var/lib/grafana). I can only guess this is just support for changing the user Grafana is running with after Grafana's database has already been created (so in case you'd want to change runtime user for an existing installation).

I can confirm disabling the chown init container run worked for me for a fresh installation of kube-prometheus-stack v 16.12.0.

If you don't plan on changing the user Grafana is running with for an existing installation you should be safe with disabling the init container.

**Comment by dolgovas** [comment]
yohoo! i think that we have work solution from another grafana helm repo
https://github.com/helm/charts/pull/10519/commits/0bfdfe7e48cf5788ad9833cadcd39c3fab05ca15
may be. You can apply this fix?

**Comment by aksh-sood** [comment]
The grafana pod started running and i am able to access the dashboard but the logs of grafana pod show error="database is locked" after following the above comments

**Comment by zanhsieh** [comment]
Psp deprecated. This issue is no longer valid. Close it.
