### ISSUE TITLE
[loki-distributed] Provide loki configuration not as string

### ISSUE THREAD

**Issue by dbluxo** [grafana/helm-charts#433]
The README says:

> Note that `loki.config` must be configured as string.
That's required because it is passed through the `tpl` function in order to support templating.
This means that a complete configuration needs to be supplied to the charts which is a good thing anyways.
Also, this allows using a separate YAML file which can be passed in using `--set-file loki.config=/path/to/config.yaml`.

I don't understand the reasoning or the great benefit of it.

In my opinion it would be much more advantageous to use a "normal" YAML structure here, because:

1. via a YAML linter you would be able to detect "errors" in the config
2. we would have a syntax highlighting within the config part
3. you could overwrite individual values of the chart without always having to specify the huge config

Templating would also work with the `tpl` function in the configmap template by using:

```
data:
  config.yaml: |
    {{- tpl (toYaml .Values.loki.config) . | nindent 4 }}
```

Am I missing something? What is your opinion on this? I would be happy to provide a PR for this.

**Comment by stevehipwell** [comment]
It's not just the config where this is an issue, affinity also incorrectly uses a string for the same quoted reason. @dbluxo it might be worth creating a PR for this even if just as a draft?

**Comment by dbluxo** [comment]
In the PR, this proposal was rejected.
