### ISSUE TITLE
[loki-distributed] Change the podManagementPolicy of the StatefulSets to "Parallel"

### ISSUE THREAD

**Issue by sherifkayad** [grafana/helm-charts#435]
Based on some problems we were facing with Loki in the last couple of days as well as reading through the behavior here https://github.com/cortexproject/cortex/issues/1521#issuecomment-640149530, it seems like in some case we end up by a very long to infinite loop of Loki ingesters not starting causing the whole cluster to fail for a long time. In case of the cluster failure and this kind of loop described in the use case we sometimes needed to delete the StatefulSet of the ingesters and re-create it. Which of course is a bad practice.

**The scenario is as follows:**
- Loki Distributed cluster with 3 Ingesters, 3 queriers, .. etc.
- Node outage on EKS (either deliberate or not)
- Potentially one or all the Ingesters weren't terminated gracefully (e.g. ingester-1 and ingester-2)
- Ingester-0 is now up and giving an issue that the ring can't be established as it's searching for ingester-1 and / or ingester-2
- Ingester-0 is unhealthy
- Ingester-1 and / or ingester-2 won't start because the StatefulSet is configured with "OrderedReady" Management Policy
- The whole Loki cluster is unhealthy!

**Proposed Solution:**
- Add a different Pod Management Policy to the Ingester StatefulSet (potentially also to the Querier StatefulSet) and use "Parallel" instead of the defaul "OrderedReady"
- Doing so, all replicas will start at the same time and the ring can be established even if the termination wasn't graceful

**Comment by sherifkayad** [comment]
I can submit the PR myself if you wish .. Let me know what you think.

**Comment by unguiculus** [comment]
@slim-bean @owen-d What's your take on this?

**Comment by owen-d** [comment]
I agree with this; it is how we run Loki :). See https://github.com/grafana/loki/blob/main/production/ksonnet/loki/ingester.libsonnet#L58

**Comment by sherifkayad** [comment]
@owen-d @unguiculus @slim-bean amazing! Should I submit a PR or how do you prefer proceeding further? We also need to make sure that releasing this would mean a breaking change in the Helm chart that requires existing Loki installations to manually delete the old statefulsets before upgrading with Helm

**Comment by slim-bean** [comment]
>  Loki installations to manually delete the old statefulsets before upgrading with Helm

There is a way to do this without actually having to destroy the entire cluster:

`kubectl delete statefulset ingester --cascade=false`  which I think in newer versions of kubernetes is now `--cascade=orphan`

This way you can delete the statefulset and not the pods, then reapply the new statefulset with the new pod management policy.

**Comment by sherifkayad** [comment]
@owen-d @unguiculus @slim-bean I submitted the PR #448 for your review with the fix I suggested. I upgraded the major chart version as this is a breaking change and added the needed notes in the README file.

**Comment by sherifkayad** [comment]
Thanks to @Whyeasy the PR was merged to main and a new chart with version 0.31.0 was released. Closing this issue now
