### ISSUE TITLE
[promtail] Promtail incompatible with GKE Autopilot

### ISSUE THREAD

**Issue by ansd** [grafana/helm-charts#447]
Promtail Helm chart version: v3.5.1

As described in the [GKE Autopilot docs](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#host_options_restrictions):

> Using hostPath volumes in write mode is prohibited, while using hostPath volumes in read mode is allowed only for /var/log/ path prefixes.

Currently, the DaemonSet is [hard-coded](https://github.com/grafana/helm-charts/blob/76ef792c3d2910f2a4c4996a66c77cc65daa0074/charts/promtail/templates/daemonset.yaml#L123-L125) to read and write to hostPath `/run/promtail`.
This will make Promtail Helm chart installation fail with error:
```
failed to create resource: admission webhook "validation.gatekeeper.sh" denied the request: [denied by autogke-no-write-mode-hostpath] hostPath volume run in container promtail is accessed in write mode; disallowed in Autopilot.
```

Are there any plans to support Promtail for GKE Autopilot?
Our use case is shipping logs from the GKE managed K8s nodes' `/var/log/pods/` directories to Loki.

**Comment by jcortejoso** [comment]
Any update on this? I'd be interested on supporting it too.

**Comment by rsteenwyk** [comment]
I'm interested in getting this supported as well or learning about any workarounds.
