### ISSUE TITLE
Grafana 8.0 Alert rules

### ISSUE THREAD

**Issue by dsiperek-vendavo** [grafana/helm-charts#493]
With Grafana 8 released it seems we need a way to add alert rules and notification policies.  Maybe this is already possible and is just not documented?

**Comment by booleanbetrayal** [comment]
It would be great to support some sort of IoC paradigm for Helm along the new Alerts feature. Currently debating adoption right now because it would mean taking our Alerts out of panel configuration / K8s ConfigMaps. Having Helm values or ConfigMap support would be fantastic!

**Comment by dsiperek-vendavo** [comment]
Contact points also don't work anymore it seems after Grafana upgrade to 8.0.0 with new alerting features.

**Comment by JohnnyQQQQ** [comment]
Provisioning is not supported for Grafana 8 Alerts at this point. We know that this is essential to a lot of users - especially if you manage a lot of rules. We have it on our Roadmap and track the progress here https://github.com/grafana/grafana/issues/36153

**Comment by shinebayar-g** [comment]
Thanks for the update! @JohnnyQQQQ

**Comment by JohnnyQQQQ** [comment]
Now that file provisioning and terraform are supported by Grafana Alerting, I'll close this issue.
