### ISSUE TITLE
Grafana Helm install fails with boolean in ingress annotation

### ISSUE THREAD

**Issue by tuxpeople** [grafana/helm-charts#540]
I got this error (I'm using Flux2):

```
Helm install failed: template: grafana/templates/ingress.yaml:23:23: executing "grafana/templates/ingress.yaml" at <$value>: wrong type for value; expected string; got bool
```

The corresponding part in the template is this
https://github.com/grafana/helm-charts/blob/0a2deec6784b58e06a6794593652ba62e1c706bf/charts/grafana/templates/ingress.yaml#L21-L25

The root cause may be this annotation I have:

```
external-dns/is-public: true
```

When I remove the annotation, it works.

**Comment by Skaronator** [comment]
Annotations should always we a string in Kubernetes. While it is possible for Helm to convert this to a string it should be good habit to always use strings for annotations.

**Comment by tuxpeople** [comment]
Thanks @Skaronator for the fast reply. Regardless if annotations should be string or not, it's still a bug in my view: 

- If annotations should always be a string, we can consider "true" as a string. So I consider it as a bug if the chart handles the string "true" as a boolean.
- If we say annotations can be a boolean, I consider it as a bug if the chart cannot handle a boolean.

During my research, I found this issue: https://github.com/replicatedhq/kots/issues/586 which may help here. The question is: Is it a bug in the chart or in helm. Or can one do something in the chart to avoid this issue?

If you go trough this list [here](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations), you see it's at least not uncommon to have "true" or "false" in annotations.

**Comment by metasim** [comment]
@tuxpeople The K8S documentation is pretty clear that annotations have to be strings:

> Note: The keys and the values in the map must be strings. In other words, you cannot use numeric, boolean, list or other types for either the keys or the values.

https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

**Comment by tuxpeople** [comment]
@metasim agree. For unknown reasons, it works now. The only difference between now and then is that `true` is no `"true"` but I'm sure I testet it with double-quotes back then. I'm closing this issue, as it works for me now. It was never my intention to use booleans, I just wanted to use the string `true`.
