### ISSUE TITLE
Error: parse error at (grafana/templates/_helpers.tpl:123): function "lookup" not defined

### ISSUE THREAD

**Issue by gcarcassi** [grafana/helm-charts#563]
If I try to install the grafana/grafana chart with the following simple values.yaml:
adminPassword: xxx
I get:
Error: parse error at (grafana/templates/_helpers.tpl:123): function "lookup" not defined

It works up to version 6.9.2 and doesn't work from version 6.9.3 on.

**Comment by zanhsieh** [comment]
@gcarcassi 
that's for helm 3. helm 2 support already deprecated.

**Comment by gcarcassi** [comment]
I was using helm 3, but a very old version. Updating to the latest fixed the problem. Thanks!
