### ISSUE TITLE
[loki-distributed] Support index-gateway

### ISSUE THREAD

**Issue by stevehipwell** [grafana/helm-charts#611]
The new _index-gateway_ component looks like something that should be supported in the _loki-distributed_ chart. Based on the documentation this would allow the _querier_ component to be made into a stateless deployment and remove the need for the _ruler_ deployment to have persistence, which would simplify the chart.

**Comment by luistilingue** [comment]
It'll be great.

**Comment by stevehipwell** [comment]
Is anyone currently planning on doing this work? I was half expecting it in the last release as a headline feature of the Loki release.

**Comment by luistilingue** [comment]
Any news?

**Comment by sherifkayad** [comment]
@luistilingue @stevehipwell I could try to give it a spin with a PR .. I would need some support testing that though. Would you be able to help me with testing and validating?

**Comment by stevehipwell** [comment]
@sherifkayad I'd be happy to test your changes. This would be easiest if it was to be sooner than later as we're currently working on integrating _loki-distributed_ into a cluster template and as such are actively testing it.

**Comment by sherifkayad** [comment]
@stevehipwell I linked my PR for that. Would be great if you can have a look and give it some rounds of testing. Feedback is much welcome.

**Comment by stevehipwell** [comment]
Closed by https://github.com/grafana/helm-charts/pull/649.
