### ISSUE TITLE
Grafana login failed

### ISSUE THREAD

**Issue by Ganaik009** [grafana/helm-charts#656]
![image](https://user-images.githubusercontent.com/71316102/131808111-1c36bf7a-5933-466d-8d9d-c5e2a478b7c5.png)
![image](https://user-images.githubusercontent.com/71316102/131808237-b0a92fd5-0544-45f9-ad7e-a34a355ad7d6.png)
![image](https://user-images.githubusercontent.com/71316102/131808919-bb9bb4d0-7874-481e-89be-b73aa20f3bb9.png)

deployed grafana via helm as statefulset with pv. unable to login to to grafana ui. Please help

**Comment by dirodriguezm** [comment]
This is an old issue, but I had the same problem and I assume the reason I can't log in is because the secret should be in base64.
