### ISSUE TITLE
[grafana] Enable Gitlab token support for downloading dashboards 

### ISSUE THREAD

**Issue by Denissa89** [grafana/helm-charts#670]
Hi! Could you optionally enable the use of authorization headers in [download_dashboards.sh](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/configmap.yaml#L53) for Gitlab users: -H 'PRIVATE-TOKEN: xxxxxxxxxxxx' or the ability to throw custom headers into the script?

**Comment by lllsJllsJ** [comment]
I have create pr here https://github.com/grafana/helm-charts/pull/1673

**Comment by zanhsieh** [comment]
#1673 merged.
