### ISSUE TITLE
[helm-chart] [feature-request] define env for dashboard sidecar container

### ISSUE THREAD

**Issue by ebuildy** [grafana/helm-charts#701]
## Feature

Allow to define env variables for the dashboard sidecar container (from the Helm chart).

## Use case

dashboard sidecar must be able to download dashboard (when using URL instead of JSON definition).

Some infrastructure dont permit direct internet access, we must use a proxy to access to internet. Proxy is set via env variable.

**Comment by christophemorio** [comment]
Hi, I'm also requesting this feature.

## Use case

Set custom `LOG_LEVEL` for as allowed here: https://github.com/kiwigrid/k8s-sidecar
