### ISSUE TITLE
Question: Grafana 8 alerting - HA setup

### ISSUE THREAD

**Issue by malejpavouk** [grafana/helm-charts#747]
Hello,
Grafana 8 has new alerting mechanism and since version 8.2 this new mechanism supports high availability mode via gossip protocol (https://github.com/grafana/grafana/pull/37920). There does not seem to be any explicit support for this critical feature in this Helm chart. Is there any guidance, how to set it up with the current versions?
Thanks

**Comment by JohnnyQQQQ** [comment]
Hey 👋  sorry for not being up-to-date with the docs for this feature. I'll add some docs in the coming days. We'll also need to make a few changes if you don't use a stateful set.
