### ISSUE TITLE
Helm repo broken

### ISSUE THREAD

**Issue by stevehipwell** [grafana/helm-charts#786]
The Helm repo hosted on the `gh-pages` branch is currently broken due to the last (manual) [commit](https://github.com/grafana/helm-charts/commit/42c6214ecfca107826e0942b0ffaf980b4a7444e) not setting the `generated` field correctly (the separator is a ` ` instead of a `T`).

**Comment by torstenwalter** [comment]
Should be fixed. Sorry for that.

**Comment by philipparndt** [comment]
Just in case someone else stumbles upon this:
On Windows, I had to clear the helm cache in `%USERPROFILE%\AppData\Local\Temp\helm\repository` in order to get the broken file out of the helm cache.
