### ISSUE TITLE
Make ruler workload optionally a StatefulSet

### ISSUE THREAD

**Issue by stribb** [grafana/helm-charts#849]
Per https://grafana.com/docs/loki/latest/operations/recording-rules/#kubernetes it is recommended that the ruler workload should be in a StatefulSet rather than a Deployment.

I propose that we do this conditional on the value of `ruler.persistence.enabled`.

Let me know your thoughts. If we have broad agreement, I can craft a PR.

**Comment by paalkr** [comment]
Please let me know if you would like any help testing such a feature. I'm more then happy to contribute.
Currently I have a fully functional loki 2.4.2 helm microservices deployment running in a test cluster.

In production we still use Kustomize to deploy both Cortex and Loki, and the capability to horizontally scale the ruler is one of the main reason it's not migrate to helm yet.
