### ISSUE TITLE
[Grafana] Grafana callback link for image renderer does not support HTTPS

### ISSUE THREAD

**Issue by ethernoy** [grafana/helm-charts#889]
The GF_RENDERING_CALLBACK_URL environment variable field in Grafana helm chart is hardcoded to use HTTP as protocol. Grafana image renderer will fail to run when Grafana itself is configured to use HTTPS.

https://github.com/grafana/helm-charts/blob/4e9046c05709fbc069cf38565b4ee81d80aa09b6/charts/grafana/templates/_pod.tpl#L398

Happy to submit a PR if needed.

**Comment by zanhsieh** [comment]
@ethernoy Please do. Thank you.

**Comment by ethernoy** [comment]
> @ethernoy Please do. Thank you.

Hi, just implemented and tested my change. I have submitted the PR.
