### ISSUE TITLE
[enterprise-metrics] Update ingester rollout policy to Parallel

### ISSUE THREAD

**Issue by replay** [grafana/helm-charts#917]
When scaling up the ingesters we want that the new ingester pods get created at once instead of one-by-one, to not unnecessarily slow down rollouts.

To do this we can change the `podManagementPolicy` to `Parallel` [as described here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#parallel-pod-management)

**Comment by applike-ss** [comment]
That seems to be the case since chart version 1.0.0 (24.05.2021).

May i ask which metric you are using to scale the ingesters nicely?

**Comment by replay** [comment]
> That seems to be the case

Thanks for pointing this out

Fixed with https://github.com/grafana/helm-charts/pull/920

> which metric you are using to scale the ingesters nicely

do you mean which metric we're using to decide whether the ingesters should be scaled? we generally aim for about 1.5M active series per ingester.

**Comment by applike-ss** [comment]
> do you mean which metric we're using to decide whether the ingesters should be scaled?

Yes. We are not sure currently when/if we should scale our ingesters as the metrics they emit do not seem match anything that could be used for scaling. My first attempt was to check if we can use incoming messages per second, but that is only available on the distributors.

> we generally aim for about 1.5M active series per ingester.

Either my google-foo is bad today or this metric is not well documented. If i got you right, then you refer to `loki_store_series_total` which does not seem to relate to incoming messages (or even ingesters) but rather to the queriers.
