### ISSUE TITLE
[enterprise-logs] Make fsGroup configurable for deploying admin-api on OpenShift

### ISSUE THREAD

**Issue by basvdl** [grafana/helm-charts#922]
In order to deploy on OpenShift we need to be able to configure the fsGroup for the `admin-api deployment`.

https://github.com/grafana/helm-charts/blob/main/charts/enterprise-logs/templates/admin-api/deployment-admin-api.yaml#L45

Add same logic seen in the other deployments, to make the security context configurable via the users `values.yaml`.

**Comment by ssncferreira** [comment]
@basvdl by looking at the `values.yaml` file, the Admin API `fsGroup` is not configurable due to security concerns:
https://github.com/grafana/helm-charts/blob/837900eb54161b2dfc00a53f576d0cadc0f5dd17/charts/enterprise-logs/values.yaml#L221-L227

This was updated in issue: https://github.com/grafana/helm-charts/issues/687

@chaudum what do you think about this?

**Comment by chaudum** [comment]
@basvdl Could you explain in more detail why this is necessary on OpenShift?

**Comment by chaudum** [comment]
Does a simple configurable fsGroup value help in this case? https://github.com/grafana/helm-charts/compare/chaudum/issue-922?expand=1

**Comment by basvdl** [comment]
@chaudum I'm not an OpenShift expert... But OpenShift uses SecurityContexts which allows a range of uid's that can be used for runAsUser, runAsGroup and fsGroup. During my last GEL deployment on OpenShift, the customer was not able to create a custom SecurityContext and needed to change the fsGroup. We did this after the deployment by manually changing the yaml on the cluster.

The suggested change looks good to me! Thanks!

**Comment by ssncferreira** [comment]
Closing the issue as a fix was already merged as part of PR https://github.com/grafana/helm-charts/pull/957
Thank you @chaudum for the help 🙏
