### ISSUE TITLE
Question: Why use loki-stack instead of separate promtail, loki and grafana installs?

### ISSUE THREAD

**Issue by PhilipMay** [grafana/helm-charts#939]
I want to install promtail, loki and grafana (and prometheus).
Why should I use loki-stack instead of a separate promtail, loki and grafana install?

Is it because loki-stack makes sure that the versions are compatible to eachother?
Is that right?

Maybe you want to add this as a "FAQ" to the loki-stack README.md so ppl. know why to use it.

**Comment by smerschjohann** [comment]
I'm stuck at the same question. loki-stack is quiet out of date, so I think this is no option at all. I disabled promtail and exchanged it with the latest version as it is able to support the cri / containerd kubernetes log format.

Now I discovered that loki is rather old as well. I try to figur out which setup is the best:
1. independent promtail, loki and grafana
2. promtail, loki-simple-scalable and grafana
3. distributed, canary?

What about the integration of loki + prometheus operator, are there any recommendations on that part?

**Comment by ChrisJBurns** [comment]
I'm also wondering the same. I use the stack and enabled prometheus and I get a warning in the UI stating: `Using Loki as Prometheus data source is no longer supported and might stop working. Please use Loki data source for your Loki instance.`. But all I did was use the helm chart. I didn't realise that the version of loki and promtail was old though. That was news to me. Perhaps the `loki-stack` chart needs updating? Or at least a a description of the difference between the helm charts and what the users would normally use them for.

**Comment by ChrisJBurns** [comment]
Update:

Since my last comment over an hour ago, I've recently found that installing `loki` with the `loki-stack` whilst disabling prometheus (default to false anyways) and grafana. So that the stack only installs `loki` and `promtail`, and then installing `prometheus` and `grafana` using the following more updated chart. https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack. I've found the error that I stated in my last comment now goes away.

This comment then shed some light on how to connect Loki up as a datasource in Grafana: https://github.com/prometheus-operator/kube-prometheus/issues/555#issuecomment-635938188


So the overal result ended up like

```
                                              grafana
                                                    |
                |-------------------- | ----------------|
loki (data source)                              prometheus (data source)
```

Knowing this, I'll probably avoid using the `loki-stack` chart unless they update it to be more recent. So I'll just use the single `loki` chart instead.

**Comment by puppetninja** [comment]
I am struggling with outdated loki-stack also, but apparently it is still being maintained ? somehow loki-stack automatically configure the loki server for promtail for me, if I install them separately they are not working out of the box

**Comment by rufreakde** [comment]
What I see missing here are values.yaml defaults that work out of the box together for all helm charts!
I would have loved to use:
- Grafana
- loki-simple-scaleable
- fluent-bit
- prometheus

But if you follow the official guide not even loki works correctly. https://github.com/grafana/helm-charts/issues?q=is%3Aissue+is%3Aopen+loki-simple-scalable 

There are a lot of issues for this one helm chart alone.

loki-stack helm chart seems to at least work with default helm configuration and some simple persistance changes.

Maybe this is related to this (recommended) flag for this [Tanka](https://grafana.com/docs/loki/latest/installation/) thingy

**Comment by rufreakde** [comment]
@trevorwhitney 
> FWIW, `loki-simple-scalable` is the most actively maintained by the Loki team at GL, and is the only helm chart we run in our own cloud (most of which is jsonnet, but a few clusters are using this chart). Could you elaborate on what problems you ran into setting up `loki-simple-scalable`? That chart is working for us currently, but as it's under rapid development, there's a chance the docs have drifted and we'd love help keeping them up to date!

Hi sorry for my late reply but here is the issue with more details:
https://github.com/grafana/helm-charts/issues/921

**Comment by trevorwhitney** [comment]
moved conversation to #921.
