### ISSUE TITLE
How to configure the built-in alertmanager?

### ISSUE THREAD

**Issue by upstream-dmahlberg** [grafana/helm-charts#958]
Since Grafana 8.3, unified alerting is enabled by default for new installations. This, apparently, uses the embedded alertmanager for managing contact points, notification policies and so on. Where can I configure these using the helm chart? Searching through the values.yaml I cannot find any place to set these settings up...

**Comment by alexandrsemak** [comment]
event more I can not find any configuration in documentation only via UI

**Comment by ritubajaj89** [comment]
As per the documentation here : https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/ 
We need to enable unified alerting, but we do not have any option in values.yaml. Anyone can help with this ?

**Comment by upstream-dmahlberg** [comment]
I've looked deeper into this - what I needed is called ["provisioning"](https://grafana.com/docs/grafana/latest/administration/provisioning/) in Grafana. According to the changelog this should have been introduced to grafana in 8.3, but it's nowhere to be found in the documentation and I have not found it in the source code either. It could be that provisioning unified alerts was introduced for paying customers only, or a mistake in the changelog, or it could be simply an oversight regarding the documentation.

As far as I know, for the time being, if you want grafana alerting in kubernetes, you are stuck with the legacy alerting system. One could probably bypass the problem with an init-container sending the proper requests to grafana on application start, but I am not aware of any other solution right now.

BTW, this is a problem many have faced, as a quick google search for "grafana provisioning unified alerts" has shown. I have yet to find a thread in which anyone of the grafana dev team is actually responding to this. In my opinion, is is neither smart nor professional to automatically enable unified alerting in the official helmchart without the ability to provision alerts - for the time being, the default settings should use the "legacy" alerting system.

**Comment by tooptoop4** [comment]
@upstream-dmahlberg how to use the legacy system via helm?

**Comment by upstream-dmahlberg** [comment]
@tooptoop4 Alerts in the legacy system are part of dashboards. You need to create a Dashboard in Grafana as .json File ( or export an existing via the settings menu in the upper right corner). I'd create a folder in my helm chart directory - so, next to Charts.yaml - called "dashboards". Then, you need to state the .json [according to documentation](https://github.com/grafana/helm-charts/tree/main/charts/grafana#import-dashboards) or [via the sidecar](https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-dashboards).

**Comment by ritubajaj89** [comment]
I am trying to upgrade grafana from 7.5.5 to version 8.3 via helm charts but unfortunately I get below error: 
err="failed to determine the status of alerting engine. Enable either legacy or unified alerting explicitly and try again".

If in case we want to use legacy alerting system, we still need to specify the same somewhere. (Can't figure out where). We have dashboards folder with necessary configs but still upgrade won't work. 

@upstream-dmahlberg  - Which version are you currently running ?

**Comment by upstream-dmahlberg** [comment]
I'm on 8.3.3. In this case, try adding the following lines to your values.yaml:

```yaml
  grafana:
    grafana.ini:
      unified_alerting:
        enabled: false
      alerting:
        enabled: true
```

**Comment by rearranged** [comment]
Some related issues:
https://github.com/grafana/helm-charts/issues/493
https://github.com/grafana/grafana/issues/36153


It seems, that this is not supported yet.

**Comment by Dima-Diachenko-work** [comment]
It's already released and supported. Check official site documentations.
I have implemented new Grafana Alerting provisioning.

I think this issue could be closed.

**Comment by upstream-dmahlberg** [comment]
Hi @Dima-Diachenko-work , thanks for reaching out. I will close this Issue now, but I did not test this since this issue was opened a year ago and we long moved on to a different solution.
