### ISSUE TITLE
[loki-distributed] use yaml for loki config, and component affinities config instead of strings

### ISSUE THREAD

**Issue by wondersd** [grafana/helm-charts#978]
https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed#example-configuration-using-memberlist-boltdb-shipper-and-s3-for-storage

In order to make basic configurations for object storage, schemas, or altertmangers urls a user must redefine the entire config file.

The given rational for this is not entirely correct.

> Note that loki.config must be configured as string. That’s required because it is passed through the tpl function in order to support templating.

An alternative can be seen in loki-simple-scalable, https://github.com/grafana/helm-charts/blob/main/charts/loki-simple-scalable/values.yaml#L62-L97, where the data structure is converted to yaml and templated as its rendered into the configmaps data.

(loki-simple-scalable still uses string for affinities)

can be handled with a little refactor of the configmaps

from:

```
data:
  config.yaml: |
    {{- tpl .Values.loki.config . | nindent 4 }}
```

to:

```
data:
  config.yaml: |
    {{- tpl (toYaml .Values.loki.config) . | nindent 4 }}
```

Keeping the formal data structure has several advantages:

  * managing many loki instances (multiple clusters) of varying histories (different lineages of schemas to preserve data over time as storage configurations were alterted)
  * chart upgrades that require a config value to change, e.g. volumemount path change, so long as that specific var hasnt been overridden it will seemlessly be updated upon upgrade.
  * when managing multiple instances of loki being able to tune loki configuration for a given loki instance while still largely following the same shared base of configuration. While possible to add placeholders in the config template string, it's untenable to add one for every possible loki configuration variable to allow tweaks when something unexpected goes wrong or a specific instances needs to modify a yet unused conguration.

Looking through the default `loki.config` in loki-distributed, this one go template conditional wont be transferable

https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/values.yaml#L112-L115

But everything else should work just fine. This may have to be removed and replace with a note that if indexGateway is enabled/disabled this config value will have to be modified.

This will likely be a breaking change, but i think its worth it (especially before 1.0) and hope you agree.

Until then will be using loki-simple-stable as the ability to allow for minor tweaks to configuration to account for potential production issues is very important.

**Comment by stevehipwell** [comment]
This has been attempted before and doesn't work, there are a number of closed issues and PRs in this repo that can easily be found to collaborate this. Basically you shouldn't use `tpl (toYaml .Values.loki.config) .` as it only works in the simplest of cases.

I have been looking into this for a few months now as the current pattern of having to declare the whole config means that there is no way to keep chart defaults. There are a couple of ways to approach this but no perfect solution, the options are as follows.

1. Allow either structured config _OR_ a string on the root value e.g. `config`
  - This is backwards compatible
  - This doesn't work with any templating
2. Allow either structured config _OR_ a string on sub-keys
  - This is backwards compatible
  - Templating works on string keys
  - Some sub-keys have complex config and require templating
3. Generate the config with a custom template
  - Probably not backwards compatible
  - Needs knowledge of config encoded in the chart

Option 3 is probably the right way forward for the config, affinities could use a custom template with placeholder to support selector labels. I plan on opening a draft PR with some of this in place to look at the feasibility.

**Comment by wondersd** [comment]
I think there might be a way to have it both ways.

1) keep `loki.config` as a string template, containing chart defaults/complete overrides by users
2) add `loki.structuredConfig` to be structured data overrides by the user
3) configmap renders the `loki.config` string template into yaml, parses that yaml, deep merges the resultant structure with `loki.structuredConfig` and finally renders that back into yaml

```
{{- if not .Values.loki.existingSecretForConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- mergeOverwrite (tpl .Values.loki.config . | fromYaml) .Values.loki.structuredConfig | toYaml | nindent 4 }}
{{- end -}}
```

This will be backwards compatible, continues the use of complex templating in the chart defaults or existing overrides to `loki.config`, and allows the user to selectively override any arbitrary value if required without needed chart maintainers to make explicit provisions for such an override.

Small caveat to the last statement when it comes to array structures, but thats something every chart has to grapple with so nothing new there.

**Comment by stevehipwell** [comment]
@wondersd I like this approach if it works. Have you tested nested key merging?

**Comment by wondersd** [comment]
@stevehipwell I have, seems to work well

```
$ helm template . 
...
---
# Source: loki-distributed/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-loki-distributed
  labels:
    helm.sh/chart: loki-distributed-0.40.0
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "2.4.2"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0s
    compactor:
      shared_store: filesystem
    distributor:
      ring:
        kvstore:
          store: memberlist
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      tail_proxy_url: http://RELEASE-NAME-loki-distributed-querier:3100
    frontend_worker:
      frontend_address: RELEASE-NAME-loki-distributed-query-frontend:9095
    ingester:
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_idle_period: 30m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    memberlist:
      join_members:
      - RELEASE-NAME-loki-distributed-memberlist
    query_range:
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h
      split_queries_by_interval: 15m
    ruler:
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      storage:
        local:
          directory: /etc/loki/rules
        type: local
    schema_config:
      configs:
      - from: "2020-09-07"
        index:
          period: 24h
          prefix: loki_index_
        object_store: filesystem
        schema: v11
        store: boltdb-shipper
    server:
      http_listen_port: 3100
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
```

```
$ helm template . --set-string=loki.structuredConfig.ruler.alertmanager_url=https://ffooooo
...
---
# Source: loki-distributed/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-loki-distributed
  labels:
    helm.sh/chart: loki-distributed-0.40.0
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "2.4.2"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0s
    compactor:
      shared_store: filesystem
    distributor:
      ring:
        kvstore:
          store: memberlist
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      tail_proxy_url: http://RELEASE-NAME-loki-distributed-querier:3100
    frontend_worker:
      frontend_address: RELEASE-NAME-loki-distributed-query-frontend:9095
    ingester:
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_idle_period: 30m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    memberlist:
      join_members:
      - RELEASE-NAME-loki-distributed-memberlist
    query_range:
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h
      split_queries_by_interval: 15m
    ruler:
      alertmanager_url: https://ffooooo
      external_url: https://alertmanager.xx
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      storage:
        local:
          directory: /etc/loki/rules
        type: local
    schema_config:
      configs:
      - from: "2020-09-07"
        index:
          period: 24h
          prefix: loki_index_
        object_store: filesystem
        schema: v11
        store: boltdb-shipper
    server:
      http_listen_port: 3100
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
```

Will make a pr with the changes
